### ISSUE TITLE
Cleaning up _loaded.from_ in SITES and MEASURENTS

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#100]
@teixeirak ,

I was able to fill in 476 missing _loaded.from_ values in SITES table, based on MEASUREMENTS table (when _loaded.from_ was unique in MEASUREMENTS)

But,
- [ ] I noticed that a lot of the measurements loaded from "Anderson_2006_toba" are from sites that have "Bety-DB data download 4/10/2014 (Matlab output)" in SITES table.

- [ ] Other inconsistencies are:

SITES loaded.from|MEASUREMENTS loaded.from
--|--
 Luyssaert_2007_cbob|Baldocchi_2008_bott
Yu_2014_hcdu|Baldocchi_2008_bott
Yu_2014_hcdu; Baldocchi_2008_bott|Baldocchi_2008_bott           
 Luyssaert_2007_cbob|Yu_2014_hcdu   

Any recommendation on this?

**Comment by teixeirak** [comment]
Please replace "Bety-DB data download 4/10/2014 (Matlab output)"  with "Anderson_2006_toba" in all cases. If there are any other cases where sites loaded.from is "Bety-DB data download 4/10/2014 (Matlab output)"  and the measurements table has a study referenced in loaded.from, replace these as well.

**Comment by teixeirak** [comment]
Regarding the other inconsistencies, I believe that all of these will be eddy flux sites. It is not a problem if site data and measurements data were pulled from separate studies, so long as the measurements are linked to the correct site (as they all are, barring unknown errors).  Please leave the references in both tables as they are.

**Comment by ValentineHerr** [comment]
ok thanks

**Comment by teixeirak** [comment]
Leave as they are.
