### ISSUE TITLE
tropical extratropical

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#107]
@teixeirak ,
I noticed that the third plot of site "Biology of Forest Growth experimental plantation in Pierces Creek Forest" in PLOTS is "tropical' while the 2 others are extractropical. All plots of that site are "extratropical" in HISTORY.
Any idea why ? It looks like there is 50 other sites in that case.

Also there are missing entries (79 total) for that column in HISTORY .

Wouldn't it make more sense to have that column in SITES table?

**Comment by teixeirak** [comment]
Those were supposed to be deleted.
