### ISSUE TITLE
Metadata for plot.name confusing

### ISSUE THREAD

**Issue by mcgregorian1** [forc-db/ForC#110]
In the [measurements metadata](https://github.com/forc-db/ForC/blob/master/metadata/measurements_metadata.csv)

**Sites.sitename** = Unique site identifier name for the site at which the measurement was made
**Plot.name** = Unique plot identifier name for the plot in which the measurement was made

In the data for measurements, the site name for Yasuni for example is "Yasuni CTFS-ForestGEO plot" and the plot name is "25-ha forest dynamics plot (western half of 50-ha forest dynamics plot)".

There are multiple entries for Yasuni in this matter. I'm currently going through the add-data-process in the context of determining if my new data (Chave_2008) already has site equivalents in the existing data. When I got to this part, I assumed I would be looking for fully unique values in plot.name, similar to the different site names I found in sites.sitename.

In revising this guide, should the metadata be saying instead that for new data of an existing site, the researcher only has to search in sites.sitename? Then when adding the data, they would copy the same sites.sitename plus the same plot.name?

If this doesn't make sense, I can explain it as well.

**Comment by teixeirak** [comment]
There are many sites (e.g., Yasuni) with just one plot associated to the site. However, there are also sites with multiple plots. The metadata is somewhat wrong in calling plot name unique, as its only necessarily unique within each site.  I’ll fix that.

Does this clarify the issue?
