### ISSUE TITLE
Issues with MEASUREMENTS.md

### ISSUE THREAD

**Issue by mcgregorian1** [forc-db/ForC#115]
- [x] 1.	In some columns, it says codes are explained in other tables (other .csv files). This wasn’t too clear for me as a general user at the outset (because I was mainly looking at Github online as opposed to only the local files); could the associated tables be hyperlinked to the measurements metadata? The columns I’m talking about are below, and the associated Github links are with them:
- [x] a.	6/F (dominant.veg), and [pft.csv](https://github.com/forc-db/ForC/blob/master/data/ForC_pft.csv).
- [x] b.	9/I (variable.name), and [variables.csv](https://github.com/forc-db/ForC/blob/master/data/ForC_variables.csv).
- [x] c.	11/K, 13/M, and 15/O, for [LOC explanation](https://github.com/forc-db/ForC/blob/master/metadata/dateLOC.csv). 
- [x] d.	4/D (plot.area) in [history_metadata.csv](https://github.com/forc-db/ForC/blob/master/metadata/history_metadata.csv).

*\*This only matters if we think users will not be using the local copies of these. The main reason this came up for me as an issue is because I was looking at the metadata online.*

These below are general questions.
- [ ] 2.	In measurements 18/R (stat.name), if my stat.name is 95%CI, do I still need to put 95% for 19/S? I was looking through the other measurement data and didn’t see anything.
- [x] 3.	In Column 20/T (area.sampled), metadata includes unit, but until I manually opened this from my local copy I didn’t see this. This might be an issue if someone like me operates mostly out of Github online.
- [x] a.	This is also an issue in history_metadata.csv in Column 4/D.
- [x] b.	Should we make a note in the How-to document that says specifically to only work with local copies?
- [x] 4.	For Column 22/V methodology, I’m looking at the csv and it seems it can be cleaned up. 
- [x] a.	There are duplicate entries (e.g. 447 and 445 (both Meakem_2017_rots).
- [x] b.	Numbers are out of order. Unsure if this was relevant.
- [ ] 5.	In measurements Columns 31/AE – 47/AU, these refer to values generated by R-scripts, and are not relevant to users entering data. Move these perhaps to a separate metadata for database admins.
- [ ] a.	This is also the same for the sites.csv Columns 30/AD-39/AM. These columns are not relevant to general user.

**Comment by mcgregorian1** [comment]
1. It turns out I can't add the links to the .csv file without creating a separate column. I'm not sure you want to do that?
4. Sounds good. I guess I didn't see the other variables part (I think I was looking online for that one).
5. Maybe. I think either we put that column as the divider between the two kinds of fields, or we make a specific note in the How-to about that.

**Comment by teixeirak** [comment]
1. No, it’s not necessary.
3. Let’s do that. Call the field something like “populated.by”. Add to all metadata files, with options manual entry, script, external database.

**Comment by mcgregorian1** [comment]
3. Ok I can do that for the measurements_metadata and the sites_metadata.

I'm not sure which fields are populated by external database. Do you mean the fields that are linked to other .csvs? I'll fill in these two files but I'll create a pull request so you can double check that.

**Comment by teixeirak** [comment]
Thanks! I have reviewed and updated the metadata appropriately (recent commit).
