### ISSUE TITLE
Issues with HISTORY_metadata

### ISSUE THREAD

**Issue by mcgregorian1** [forc-db/ForC#116]
- [ ] 6.	Column 1/A (history.ID), unclear if users enter this by themselves, or is it automatically generated?
- [ ] 7.	Column 8/H and 9/I (plot history event): can we hyperlink to [histtype](https://github.com/forc-db/ForC/blob/master/data/ForC_histtype.csv)? Only relevant if viewing .md online
- [ ] 8.	Column 15/N: should read as Column 15/O. This looks like it is not relevant to general user.

9.	There is a Column 16/P (tropical.extratropical) that is not listed in metadata. Also appears to be not relevant to general user (*you already have an issue with this*)

**Comment by teixeirak** [comment]
6. Best if user enters it.
7. We've dealt wit htihs.
8. Clarified in metadata
9. This has been deleted.
