### ISSUE TITLE
Issues with metadata (general)

### ISSUE THREAD

**Issue by mcgregorian1** [forc-db/ForC#117]
*# 13 refers back to Step 6 of the updated [How-to guide](https://github.com/forc-db/ForC/blob/master/how_to/edit_the_data_(overview).md).*

- [x] 13.	Should we say that if you find the site already listed (when doing a background check before entering data), then you should base your entry for Measurements.csv Columns B-H on what’s already been entered (for site descriptors)?
- [x] a.	For ex, I’m entering new data for BCI, whose descriptors of old growth, tropical deciduous broadleaf and 50ha site haven’t changed. However, maybe this is only in my mind because I’m entering data specifically for CTFS-ForestGEO sites.
- [x] i.	Now that I’m thinking about it, would it make sense to make a separate, short .csv where we list (via R-scripts) each site plus their descriptors Columns B-F? This way users could easily follow the same identifiers for sites we already have data on. 
- [x] ii.	In other words, it would be an extension of the sites.csv.
- [x] 1.	I say this because for example I was searching for Edoro and Lenda, which didn’t come up when I did “control f” in the measurements despite “Ituri-Edoro” being one of the entries. Unsure if this is relevant.

The questions below are general.

- [ ] 10.	For Methodology, Should there be instructions in the data How-to guide for users to input a new methodology entry? Or should the instructions be to flag this for moderators to review the methodology before adding it?
11.	Regarding the missing_value_codes.csv, this is minor, but I think NRA = Not readily available should have a description stating
- [x] a.	“Information was not made readily available by the authors (e.g. no ready[?] access to the publication, language barrier).” This clarifies a bit more than the current description.
- [x] 12.	Regarding citations.csv: In the guide for entering data, we currently say that users should add data by adding new rows or updating the .csv files. Should we add a modifier saying to not worry about putting things in alphabetical order? Or does this not matter? 
- [x] a.	In citations metadata: does citation.ID include basic words like a, of, or, for, in? Should this be clarified?
- [x] i.	E.g. Chave_2008 Assessing Evidence for a Pervasive Alteration in Tropical Tree Communities
- [x] ii.	Chave_2008_aefa
- [x] iii.	Chave_2008_aepa
- [x] 14.	In the ForC_allometry.csv (data), Chave_2005_taai is listed twice, with one entry being “NAC.”

**Comment by teixeirak** [comment]
Regarding 13b, I've thought of moving veg descriptors from `MEASUREMENTS` to `PLOTS`. however, this can change (in theory-- I'm not sure if we have any cases where it actually has changed enough).

**Comment by teixeirak** [comment]
Regarding "1.", I'm confused...

**Comment by teixeirak** [comment]
Regarding 13 and 10, would it make sense to create separate how-to guides for each data table?

**Comment by teixeirak** [comment]
11. That info is in the [missing values codes table](https://github.com/forc-db/ForC/blob/master/metadata/missing%20value%20codes.csv).

**Comment by teixeirak** [comment]
12- clarified in citations metadata file.

**Comment by teixeirak** [comment]
14. fixed.

**Comment by mcgregorian1** [comment]
> Regarding "1.", I'm confused...

The CTFS sites for Ituri-Edoro and Ituri-Lenda in Chave_2008 were labeled as only "Ituri" and "Lenda." When I was searching for these sites in the measurements.csv file, I did a control-find command for the names, but they didn't show up. I later discovered they were labeled as *Ituri-* Edoro and Lenda.

  - My concern is simply that I almost started entering duplicate sites for these because the "find"command couldn't discern the names. I think this might be an issue for people in the future.



> Regarding 13 and 10, would it make sense to create separate how-to guides for each data table?

It's possible. I'm fine making one, but I wasn't sure if that might be too many metadata files. What do you think?

**Comment by teixeirak** [comment]
Regarding instructions for entering data in each sheet, I'm thinking more of a detailed README that could walk an undergrad student (for example) through the process of data entry. Creating these probably isn't a high priority.

**Comment by teixeirak** [comment]
Regarding this:

> 10. For Methodology, Should there be instructions in the data How-to guide for users to input a new methodology entry? Or should the instructions be to flag this for moderators to review the methodology before adding it?

I think our level of detail for methodology instructions is similar to other tables (i.e., basically no info in the how-to guide, but presumably sufficient instructions in the metadata). @mcgregorian1, please feel free to edit the instructions or metadata to address any specific points of confusion.

**Comment by mcgregorian1** [comment]
The only things I'm thinking of for clarification are a list for the method.category, since the metadata doesn't fully describe what would count as a category/how categories are decided. 

Also, I'm assuming this would come later but we haven't decided yet about grouping sites together without a super site name right? Would this method.category be a similar approach to the grouping by site names we were talking about?

@beckybanbury can you look at the methodology tables, and note if there's anything you see as confusing for a random researcher who needs to update the table?

**Comment by beckybanbury** [comment]
@mcgregorian1, I remember finding the measurements metadata for this unclear when I was first entering data; it isn't clear whether new methodologies need to be added to that table, and how that should be done. When I was looking to include a method.ID for the study I was looking at, the fact that there are several entries with multiple citations made it unclear as to whether the method.citation referred to papers that used the method, or the papers in which the method was developed/defined. This meant it was confusing to know whether assigning method ID was based on the specific method.citation or finding the method.notes that best described the method used. 

Looking at the actual methods tables and the metadata, I can't tell how the method.ID is generated (numbers seem to be in a random order!), so I'm unsure how new IDs would be added.

Let me know if anything I've said is unclear!

**Comment by mcgregorian1** [comment]
> When I was looking to include a method.ID for the study I was looking at, the fact that there are several entries with multiple citations made it unclear as to whether the method.citation referred to papers that used the method, or the papers in which the method was developed/defined. This meant it was confusing to know whether assigning method ID was based on the specific method.citation or finding the method.notes that best described the method used.

Overall this seems like a question for @teixeirak. It appears we need to 

1. define in the metadata the threshold for when a methodology is different enough from an existing one in the database to warrant creating a new method.ID.

2. clarify how to add new methodology. Should people search by variable first, then method.notes, then method.citation (in case they're using the same citation), and then figure out what method best fits their data, up to the threshold set above?
  - define how to add a new method.ID. It looks like before people add any new methodology, they must first filter the method.ID column by ascending values, then add the next number up.

3. clarify the use of multiple method.citations for a single method in the metadata.
