### ISSUE TITLE
issues in plothistory and measurements (plot.name, duplicate entries)

### ISSUE THREAD

**Issue by mmw590** [forc-db/ForC#12]
1. plot.names not matching between measurements and plothistory:
- changed spelling: 'Terra' changed to 'terra'. 'firme' changed to 'firma'
- plot.names in measurements manually changed to be follow what was in plothistory.

2. duplicate entries in plothistory with no extra information (all NACs). 
- these entries were manually removed and attached here
[TropForC_plothistory_duplicatesremoved.xlsx](https://github.com/forc-db/ForC/files/836095/TropForC_plothistory_duplicatesremoved.xlsx)

**Comment by teixeirak** [comment]
Thanks! These are now in the master branch.

**Comment by teixeirak** [comment]
I spoke too soon. I have not yet been successful in merging into the master branch. Reopening this issue.

**Comment by mmw590** [comment]
I can just upload the files into a new branch

**Comment by teixeirak** [comment]
If you can figure out how to resolve it, that would be wonderful!



On Mar 13, 2017, at 3:01 PM, Maria Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


I can just upload the files into a new branch

**Comment by teixeirak** [comment]
resolved with pull request #14 .
