### ISSUE TITLE
95%CI discrepancy

### ISSUE THREAD

**Issue by mcgregorian1** [forc-db/ForC#121]
In ForC_measurements.csv, the 95%CI is listed for other sites as only one value. Some sites have in the notes that this is the upper value, whereas other sites have no values.

Is there a way you want both values entered, since it is an interval?

The [metadata](https://github.com/forc-db/ForC/blob/master/metadata/measurements_metadata.csv) (Columns R/S) does not say anything about this.

**Comment by teixeirak** [comment]
Frankly, this is a database design flaw. I changed the metadata to go with the convention that we report based on the upper 95%CI.
