### ISSUE TITLE
Ideas for clarifying data entry

### ISSUE THREAD

**Issue by mcgregorian1** [forc-db/ForC#129]
## Ideas for Methodology

1. Ideal organization of the method.id records in Methodology table would be a finite number of broad methodological approaches in method.category, and unlimited number of variants on those.

    a.  Before assigning a number, its good to see if there's already a record specifying the same approach (e.g., 446 could apply to multiple ForestGEO studies). If it doesn't exist, create a new unique number (higher than current max). 

    b.  For example, record 446 is the same methdology as 452, but ultimately 446 was used to obtain delta.agb_C, whereas 452 was used to measure delta.agb_OM. It would make sense to merge those by giving them the same ID number followed by decimals (e.g. 446.1, 446.2).

    c. We want to fix up the NPP and GPP records for the Bukit Timah Primary and Secondary data (from [this merge/pullrequest](https://github.com/forc-db/ForC/commit/37646ec0308c108ee64cb43a7378f6c468a756e9).

**Comment by teixeirak** [comment]
clarification- Bukit Timah data entered in that pull request did not include any GPP or NPP. Becky's project will focus on productivity, but the Bukit Timah data was just practice entering data.
