### ISSUE TITLE
fix units on DeAngelis_1981_pofe data

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#131]
@beckybanbury, It looks like the units on this latest pull request are wrong.  Please convert to Mg/ha, and also check that _OM or _C subscripts on the variable names are correct.

**Comment by beckybanbury** [comment]
Ah okay - thanks for flagging that!

**Comment by beckybanbury** [comment]
@teixeirak I've converted the units - corrected version is in the new pull request

**Comment by teixeirak** [comment]
thanks!
