### ISSUE TITLE
run QA/QC check on new records, fix any problems

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#135]
@beckybanbury (and @mcgregorian1)

This is a general issue I want to bring you both up to speed with, with a specific example for Becky to deal with.

We have code [here](https://github.com/forc-db/ForC/tree/master/scripts/QA_QC) to check new data to ensure that all measurements have corresponding site/plot/ history records, whether numerical values fall within the expected range, etc.  Assuming you're able to run it without problem, could you please start doing so after each new data entry, before submitting a pull request? 

@beckybanbury, its currently generating a few errors from your latest import. I think there may be a typo in one of the site names  (Talllish Oak_2) that makes it show up as not matching. That's the only real error I noticed f=from a quick look.

There's also missing plot data, as we need to run [this script](https://github.com/forc-db/ForC/tree/master/scripts/Database_manipulation/Generate%20PLOTS%20from%20HISTORY) to generate a new version of plots. Please run that if you're able to do so without a problem.

@ValentineHerr is planning to write a wrapper script to do all the updates at once, but for now we have multiple scripts that need to be run when new data are added.

**Comment by beckybanbury** [comment]
@teixeirak I've run both codes + created pull request for the new plots data. 

When I run the code to check errors it is still saying that I have measurements with no corresponding plot record. I've checked all the sites I entered, and they now have plot records, so I'm not sure where this error is coming from. I will run it again after the branch has been merged to double check.

**Comment by teixeirak** [comment]
Thanks, looks great! The R code produces files (e.g., "m_no_p") to indicate which records are problematic. I'll look into the ones with problems.
