### ISSUE TITLE
Please provide original study in citation.ID, or at least in source.notes

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#139]
@beckybanbury, specifically regarding pull request #138, but also in general...

Please provide original study in citation.ID, or at least in source.notes. This will be very important for identifying duplicates (and I could see from a quick look at the Taylor data that there are some).

**Comment by beckybanbury** [comment]
@teixeirak, no problem, I'll update. Does it work to put two citation IDs in the citation.ID column? If I enter the original study info in the source.notes, does it still need to be in name_year_fourletters format?

 Regarding duplicates, I have been checking whether the source citation is already entered in the spreadsheet; in a lot of cases they are, but there is no entry for variable ANPP_1_OM (which is what I'm working with), and so I have entered that data. I assumed that this would not count as a duplicate entry; is that correct?

**Comment by teixeirak** [comment]
I'm glad you've been checking. You're really on top of it!

We always want Citation.ID in the standard format, with a corresponding record in citations table. Some of the studies are already in there. If its too time consuming at this point to do that, you can enter original studies in the notes to facilitate that process later, but its preferable to fill it in completely. 

Citation.ID should have just one citation (original, not Taylor). In case there are two you can indicate that in the notes, but try to identify which is primary.
