### ISSUE TITLE
Adding data from FLUXNET

### ISSUE THREAD

**Issue by beckybanbury** [forc-db/ForC#149]
@teixeirak , data are downloaded.

Within each file, I think there's different values of GPP:
1) GPP_NT_VUT_REF: "GPP estimated from nighttime partitioning method, reference selected from GPP versions using model efficiency (MEF)"
2) GPP_NT_VUT_XX: "GPP estimated from nighttime partitioning method (with XX = 05, 16, 25, 50, 75, 84, 95)"
3) GPP_DT_VUT_REF: "GPP estimated from daytime partitioning method, reference selected from GPP versions using model efficiency (MEF)"
4) GPP_DT_VUT_XX: "GPP estimated from daytime partitioning method (with XX = 05, 16, 25, 50, 75, 84, 95)"

I'm not familiar with the methods so I don't know which are the correct values to add to the database; do you have any ideas, or have any information about which data were previously entered from the FLUXNET database?

**Comment by teixeirak** [comment]
For the record, description of flux partitioning methods is [here](http://fluxnet.fluxdata.org/data/fluxnet2015-dataset/data-processing/).

**Comment by teixeirak** [comment]
@beckybanbury, could you please help sort out what the is the difference between _XX and _REF? 

Note: it may be worth including more than one, and then assigning priority within ForC. That way we could see whether results are sensitive to method (both of which are perfectly valid).

**Comment by teixeirak** [comment]
@beckybanbury, let's enter both GPP_NT_VUT_REF and  GPP_DT_VUT_REF. The associated methods should be:
GPP_NT_VUT_REF- GPP estimated from nighttime partitioning method (Reichstain et al 2005 GCB). Variable USTAR threshold, with reference selected from GPP versions using model efficiency (MEF). Associated citation: Reichstain et al 2005 GCB, 
GPP_DT_VUT_REF- GPP estimated from daytime partitioning method (Lasslop et al 2010 GCB). Variable USTAR threshold, with reference selected from GPP versions using model efficiency (MEF). Associated citations: Lasslop et al 2010 GCB.

**Comment by beckybanbury** [comment]
@teixeirak, okay great - thanks so much for looking at this!
