### ISSUE TITLE
plot.names missing or duplicated for multiple plots

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#158]
@teixeirak, I noticed that some _plot.name_ are NA or NAC in ForC_measurements, and I think it is messing up the GROA History import. It is only 38 measurements, maybe we can try to fill that up?

Also, @aferson found instances where _plot.name_ has been duplicated across plots. For example, in the one publication she was looking at, there was clear plot IDs (like plot A1, A2...), but, in ForC, the _plot.name_ for the corresponding records were "montain forest" across all plot IDs...
@aferson, please correct me if I did not describe correctly what you found.

So, 
 - Should @aferson, edit _plot.name_ when she finds those issues?
 - Should @aferson or I try to fill in those 38 missing _plot.name_?

**Comment by teixeirak** [comment]
I believe this was fully resolved with our in-person discussions.
Replace NA/ NAC in plot names with "unnamed"
We can edit the plot names as in the case described above, but its not a particularly high priority (unless trying to add more data from the same site).
