### ISSUE TITLE
Issue with data in ForC not matching publication

### ISSUE THREAD

**Issue by aferson** [forc-db/ForC#159]
Please review measurement ID's: 11516, 11524, 11525, 11541, 11542,11543, 11552, 11560, 11561, 11574, 11575, 11576, 11588, 11595, 11604, 11605, 11611, 11621, 11627, 11647, 11652, 11663.

We are running into the same issue that we did yesterday that the organic layer data in ForC does not match that of Sierra_2012_tcai; this time it does say that the source was digitized. But we are unsure where they are getting the numbers that they entered from, especially considering that GROA matches the literature once again.

Thank you,
Abby

**Comment by teixeirak** [comment]
Please just replace these (and probably all records from that study) with the correct values. More generally, if/when you find errors in ForC when comparing to the original study, go ahead and correct.
