### ISSUE TITLE
Aragao 2009 records

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#16]
@mmw590, In the measurements file, there are differences between Aragao 2009 records in this master version of TropForC and the original spreadsheet (2ForC, in the private repository). I'm not sure which is the correct version. Could you please take a look?

**Comment by mmw590** [comment]
2ForC is more correct (I got the values directly from Aragao 2009 - thanks past self for keeping the format conversion tables and highlights in the pdf). I did find a couple of small errors though, and fixed them.

**Comment by teixeirak** [comment]
Thanks for fixing that!

On Mar 20, 2017, at 6:33 PM, Maria Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


2ForC is more correct (I got the values directly from Aragao 2009 - thanks past self for keeping the format conversion tables and highlights in the pdf). I did find a couple of small errors though, and fixed them.

**Comment by teixeirak** [comment]
Updated in master version (currently offline).
