### ISSUE TITLE
No dates reported in Taylor_2017_tari

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#162]
@teixeirak,

I am working on revamping the script that IDs duplicated measurements.
A lot of the data entered by @beckybanbury, _loaded.from_ Taylor_2017_tari is showing up in S groups with data _loaded.from_, Luyssaert_2007_cbob_v3.3 because there is no dates in the Taylor_2017_tari database.
Filling dates in those records, would require going back to the original publications. But there is 125 different _citation.ID_ so it would take quite some time.

Do you have any thoughts about that?

We could fill in the dates when the _citation.ID_ and _stand.age_ is the same as in Luyssaert_2007_cbob_v3.3 but there would still be some questionable cases.

**Comment by beckybanbury** [comment]
All entries from Taylor_2017_tari have now been assigned dates, or assigned NI/NRA codes if appropriate based on the original publications.
