### ISSUE TITLE
update R code to work with new database structure

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#17]
Database structure has been modified a bit; @mmw590's [R code](https://github.com/forc-db/ForC/blob/master/scripts/archive/ForC_Rcode.txt) may need to be modified to run correctly.

**Comment by bpbond** [comment]
Hi @teixeirak I'd also be happy to do this--it would be a good way to get my feet wet so to speak.
Ben

**Comment by teixeirak** [comment]
That would be great, @bpbond, but with the caveat that I'm currently revising the disturbance history, so there are some more changes to come. I will try to get all this up on Github ASAP, but in the meantime feel free to contact me with questions.
