### ISSUE TITLE
Investigate missing sites in different tables

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#175]
Here I am listing sites (and I am not going into the plot level yet) that exist in one table but not another. 
The reasons might be good, like sites related to issue #126 but they might also be more complicated and reveal other issues.
@teixeirak and maybe @beckybanbury, do you have an idea why there are so many discrepancies ?

1. _sites.sitename_ in HISTORY but not in SITES nor MEASUREMENTS
     - [ ] Ducke Forest
     - [ ] FLONA Tapajos Km 67
     - [ ] Guanica State Forest
     - [ ] Gunung Mulu National Park I
     - [ ] Gunung Mulu National Park II
     - [ ] Gunung Mulu National Park III
     - [ ] Gunung Mulu National Park IV
     - [ ] Harvard Forest
     - [ ] Lumbubashi
     - [ ] OREAST,Pringle Falls RNA 1
     - [ ] OREAST,Pringle Falls RNA 2
     - [ ] OREAST,Pringle Falls RNA 3
     - [ ] QC-EOBS
     - [ ] Sikfokut
     - [ ] Sinharaja
     - [ ] Taita Experimental Station

2. _sites.sitename_ in SITES or MEASUREMENTS but not in HISTORY
    - [ ] Adelaide River
    - [ ] Arunachal Pradesh
    - [ ] Cascade Head 1
    - [ ] Cumberland Plain
    - [ ] Davos
    - [ ] Deer Canyon Preserve Pinyon Juniper Woodland
    - [ ] FT14 Kalagarh
    - [ ] Gingin
    - [ ] GLEES
    - [ ] Igapo
    - [ ] Ispra
    - [ ] Lackenberg
    - [ ] Laegern
    - [ ] Loxton
    - [ ] Luquillo Experimental Forest: Bisley watersheds 1 and 2
    - [ ] Metolius Mature
    - [ ] Metolius Young
    - [ ] MHW
    - [ ] Mongu
    - [ ] Moshiri
    - [ ] MRP
    - [ ] O site
    - [ ] Oberbarenburg
    - [ ] OREAST,Metolius RNA,MRNA
    - [ ] OREAST,Pringle Falls RNA,PF27
    - [ ] OREAST,Pringle Falls RNA,PF28
    - [ ] OREAST,Pringle Falls RNA,PF29
    - [ ] Poker Flat
    - [ ] Robson Creek
    - [ ] Seto
    - [ ] Tablelands Juniper Savanna
    - [ ] Tambopata-Candamo Reserve permanent plot TAM-03
    - [ ] Tambopata-Candamo Reserve permanent plot TAM-04
    - [ ] University of Michigan Biological Station (UMBS)
    - [ ] Valles Caldera Mixed Conifer
    - [ ] Valles Caldera Ponderosa Pine
    - [ ] Wallaby Creek
    - [ ] Web-FACE
    - [ ] Whroo
    - [ ] Willow Creek (WC)-Chequamegon National Forest
    - [ ] Wombat
    - [ ] YRP

2. _sites.sitename_ in SITES but not in MEASUREMENTS
    - [ ] Gorakhpur_S_16
    - [ ] Hungary
    - [ ] Igapo
    - [ ] Santarem
    - [ ] Tallish Ironwood_1

3. _sites.sitename_ in MEASUREMENTS but not in SITES 
    - [ ] Sikfokut

**Comment by ValentineHerr** [comment]
never mind for now.... it looks like there is a lot of hidden spaces that I did not take into account...

**Comment by ValentineHerr** [comment]
Ok I fixed some extra spaces in HISTORY and updated the lists above. So @teixeirak and @beckybanbury you can review now.

**Comment by teixeirak** [comment]
I'll let @beckybanbury take the first pass.

**Comment by ValentineHerr** [comment]
I think we can close this
