### ISSUE TITLE
history.no.info, do we want to include those plots?

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#177]
Do we want to include the ForC_simplified records that have a 1 in _history.no.info_ for the age trend in C cycle and the diagrams of C cycle ?

**Comment by ValentineHerr** [comment]
Note 1: the current plots are without them
Note 2: I actually just pushed the new version with SRDB (they were not updated in the previous push because I had forgotten to save the plots...)

**Comment by teixeirak** [comment]
Yes, please include. We will still  exclude some based on management. If not already implemented, we should exclude those with  "Managed" in their name.

**Comment by ValentineHerr** [comment]
Closing this. Note that we eventually decided to keep excluding sites with history.no.info = 1 since we are identifying managed/unmanaged sites differently with SRDB.
