### ISSUE TITLE
Differentiate natural and experimental drought in SRDB import

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#179]
Currently, natural drought and experimentally imposed drought (e.g., throughfall diversion) are both coded as "Disturbance"- "Drought" in HISTORY, following [this guidance](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/srdb/manipulations.csv). However, we need to be able to separate the two, as many analyses would want to exclude the latter but not the former. Rather than coding drought treatment as "Disturbance"- "Drought", it should be coded as hist.cat-'Management' & hist.type -'Precipitation diversion'.

**Comment by ValentineHerr** [comment]
I think the easiest way to deal with this is to update manipulation.csv
Which ones, if not all, of these SRDB Manipulation should be changed to "Management" - "Precipitation diversion" ?

- [ ]  Drought
- [ ] Drought, irrigation
- [ ] Rainfall exclusion
- [ ] Throughfall exclusion
- [ ] Warming, drought

**Comment by teixeirak** [comment]
All.

**Comment by ValentineHerr** [comment]
Ok I updated manipulation.csv.
Leaving this open until I redo the import to double checked that worked

**Comment by ValentineHerr** [comment]
@teixeirak, should this happen for all records in ForC or just SRDB? 
If SRDB only, it is done and you can close it.
