### ISSUE TITLE
clarify meaning of "Clearcut" manipulation in relation to stand age

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#180]
There are some instances in srdb where `Manipulation = Clearcut` but `Age >10`:  

 <img width="2560" alt="Screen Shot 2019-05-13 at 11 45 01 AM" src="https://user-images.githubusercontent.com/6355854/57635127-93552e00-7574-11e9-937d-f23f3258e91b.png">

The way the data are currently being imported, these don't make sense. They are assigned the reported age, which seems far too old for "clearcut treatment" studies.

@bpbond, would it be appropriate to modify the ages listed in SRDB? If not, we'll need to modify the import script.

**Comment by bpbond** [comment]
I'll go investigate those later today.

**Comment by bpbond** [comment]
```R
> filter(x, Manipulation=="Clearcut", Age_disturbance > 10)$Record_number
[1]  770 2356 4085 4086 4087 4088
```

I went back to the original studies and these were all mistakes! Good catch--thank you. Corrected.

**Comment by teixeirak** [comment]
Thanks!
