### ISSUE TITLE
SRDB import: dates on fluxes other than soil respiration

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#182]
In the initial import, we assumed that `Study_midyear` applied to Rs and not to other variables such as GPP, NPP. However, that leaves us with no date for a lot of records, when in fact `Study_midyear` would apply to many/most/all(?) of these records. Moreover, some of these records may differ only in Study_midyear (e.g., Schanis). 

@bpbond, what was the convention on dates for supplementary fluxes such as GPP, NPP, etc. Would those generally match the year of Rs? If not, perhaps we assign `Study_midyear` but indicate that year is approximate?

@ValentineHerr, please record  `Study_midyear` for supplementary fluxes and stocks in SRDB (GPP through C_soildepth). date.loc may need to be adjusted based on Ben's response to the above question.

**Comment by bpbond** [comment]
The supplementary fluxes should almost always track `Study_midyear` just as `Rs_annual` does. There may be occasional cases when the authors gave e.g. a GPP without exactly specifying the year, so could be a bit off, but should be rare.

**Comment by teixeirak** [comment]
okay, thanks. @ValentineHerr, please treat dates on these supplementary fluxes the same as Rs.

**Comment by ValentineHerr** [comment]
@teixeirak, 

currently I have :

-  if variable name **is NOT** _R_soil_C_, _R_het_litter_C_, _R_auto_root_C_, _R_het_soil_C_, _R_auto_root_C_, _R_het_soil_C_ then:
      - date <- "NAC"
      - start.date <- NA
      - end.date <- NA
      - date.loc <- 9
      - start.date.loc <- NA
      - end.date.loc <- NA

-  if variable name **IS** _R_soil_C_, _R_het_litter_C_, _R_auto_root_C_, _R_het_soil_C_, _R_auto_root_C_, _R_het_soil_C_ then:
      - date <-Study_midyear (or "NAC" if missing)
      - start.date <- Study_midyear - YearsOfData/2 (or "NAC" if Study_midyear  or YearsOfData is missing)
      - end.date <-  Study_midyear + YearsOfData/2 (or "NAC" if Study_midyear  or YearsOfData is missing)
      - date.loc <- 8
      - start.date.loc <- 7.5 or 9 start.date is "NAC"
      - end.date.loc <-  7.5 or 9 start.date is "NAC"


**Now you are saying: use second part for all variables. correct?**

**Comment by teixeirak** [comment]
correct.

**Comment by ValentineHerr** [comment]
Ok, I updated the code accordingly. Leaving open to double check with new import.
