### ISSUE TITLE
SRDB import: count records with consecutive Study_midyear as single plot

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#183]
@ValentineHerr, in cases where Study_midyear increases consecutively and Age stays the same, we have what the code thinks are separate plots when in fact we're dealing with a multi-year study at the same plot (example: Schanis). Please modify these such that we only get one plot, with age defined based on the first study date. 

Please alert me if this causes unexpected problems. I think we've been through this issue before and decided to do it the way its currently done, but now that I'm looking at the import I'm realizing that this creates a lot of unwanted false separation of plots.

**Comment by ValentineHerr** [comment]
I wrote the code to deal with that. I don't know yet what problem it can cause (I need to roll back all changes in ForC and run SRDB_import.R again to figure it out), so leaving this open for now.

**Comment by ValentineHerr** [comment]
I found a tricky example related to this.

This is data from site "Oak Ridge"
Columns indicates the stand.age, rows the study_midyear.
Numbers in the grid are the number of record in SRDB.

![image](https://user-images.githubusercontent.com/19673377/57938263-d590af00-7895-11e9-9207-671dc818c646.png)

We, as human, can see that stand with age 10 was samped in years 1997-2001 but the stand age was not updated along those years. Other plots seem to be independents. and stand age should be kept to what they are.

I don't know how to code this to handle all potential cases.... quickly enough (to be done before I leave tonight)

**Comment by ValentineHerr** [comment]
[This ](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/srdb/issue_183_not_fixed_with_code.csv) is a file with all situations that my code is not fixing. (It is easier to look at the file in Excel, ignore the X in front of stand age)
All other cases (where there is only one stand age involved) are easily fixed.

**Comment by teixeirak** [comment]
Got it. This is a tricky one to deal with. Some will obviously require manual review, but I'm wondering if there's any way to facilitate that/ code away some of the more common problems.

**Comment by teixeirak** [comment]
Here's the start of a list I'm making as I assess these:

Examples of legitimately independent plots, and would be good to exclude from this list:
- Northern Limestone Alps
- Buckingham-20

Examples that seem like they'd be solved by counting as the same plot if date is only 1/2 year off:
- BOREAS NSA-OBS
- Coweeta-WS6

**Comment by teixeirak** [comment]
The 1/2 year issue seems like it may be easily solveable, and seems to be affecting a good number. Sometimes it would be solved by rounding up, other times by rounding down.

**Comment by teixeirak** [comment]
There are a number where measurements were made in only one year. If all records are from the same study, they can be counted as legitimately separate plots and removed from the list.

**Comment by teixeirak** [comment]
When one of the ages is NAC, its a likely duplicate with another plot but requires manual review. These should be imported as is and will need to be reviewed later. Please make a list of these.

**Comment by ValentineHerr** [comment]
Can you show me an example where rounding 1/2 year would solve the problem?
And how to automatically decide if it is supposed to be rounded up or down?
I don't see the trick! :-)

**Comment by teixeirak** [comment]
Actually, this isn't dealing with consecutive years; rather, it would come in where you decide whether plots were established in the same year. If

Several examples below. In this case, if you count 1971 as the earlier year of measurement, there's a 24 year difference between the first and second measurements, and also a 24 year difference in stand age. One way to solve this (that would actually be better for plot names) would be to floor estimates of year established. We'd rarely say, "stand established in 1940.5" or "stand is 70.5" years old. This false precision is essentially what's causing a lot of these problems. 

Coweeta-WS6 ____________________________
,29,5
1971.5,0,1
1995,1,0
           
Coweeta-WS13 ____________________________
,33,9
1971.5,0,1
1995,1,0
           
Coweeta-WS17 ____________________________
,15,39
1971.5,1,0
1995,0,1
           
Coweeta-WS18 ____________________________
,44,68
1971.5,1,0
1995,0,1

**Comment by ValentineHerr** [comment]
ok, I'll use floor(Study_midyear) when attributing plot.name

**Comment by teixeirak** [comment]
@ValentineHerr, I've updated the list above. Could you please try implementing those (hopefully all pretty easy) and see how the list looks?

**Comment by ValentineHerr** [comment]
Site names are now listed in
[sites_where_age_have_been_changed](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/srdb/new_data/ForC_issue_183_sites_where_age_have_been_changed.csv)
[sites_with_NAC_and_at_least_one_other_age](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/srdb/new_data/ForC_issue_183_sites_with_NAC_and_at_least_one_other_age.csv)
[sites_legitimately_complicated](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/srdb/new_data/ForC_issue_183_sites_legitimately_complicated.csv)

**Comment by teixeirak** [comment]
Thanks. This reduces the number of sites that need review to a manageable number.

**Comment by teixeirak** [comment]
I just found an example where a single plots is falsely counted as multiple plots. It is "Kurth_2014_isrr research site in Minnesota USA", "Temperate Deciduous Forest. Stand established around 1950/1951/1952". The same study had plots of age 0-1-2 (measured in 3 consecutive years) that are treated correctly. In SRDB, age 60 is given to all 3 instances of the older plot.
