### ISSUE TITLE
SRDB: clarify stand age and disturbance

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#184]
Hmm, could be. In SRDB `Age_disturbance` should generally reset with any kind of disturbance.

_Originally posted by @bpbond in https://github.com/forc-db/ForC/issues/178#issuecomment-492230878_

This is a broader issue that we need to figure out. ForC counts stand age as the age of the oldest trees/cohort.

I think it would help to look at a few examples of this. Note that for the one example I looked up (site = R-SF), age.disturbance matched age of oldest trees (6 years), yet site was recorded as mature.

**Comment by ValentineHerr** [comment]
@teixeirak, do we have a final call on this?

**Comment by teixeirak** [comment]
I need to review some examples. Working on it.

**Comment by teixeirak** [comment]
From what I can tell after reviewing some records, we're generally getting accurate stand age from age.disturbance. Thus, I don't think we need to do anything here. (Sound right, @bpbond?)

**Comment by bpbond** [comment]
Agreed.

**Comment by teixeirak** [comment]
Good, we can close this.
