### ISSUE TITLE
SRDB: fix NAs / NACs in citation.ID

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#185]
There's a huge number of records with NA/ NAC in citation.ID. I'm not yet sure why.

**Comment by teixeirak** [comment]
@ValentineHerr , I'm not sure what's causing this-- something in the code?

An example is ForC record 22249/ SRDB record 691. Site = Fazenda Vida Nova. Study = #937, Author = Fiegl.

**Comment by ValentineHerr** [comment]
Good catch. sorry for that. 
There was a problem in the code. _citation.ID_ is populated only if _Quality_flag_ is not "Q02" but the code was not considering the possibilities where _Quality_flag_ is NA... 
I fixed it.

**Comment by ValentineHerr** [comment]
Ok, now all records coming from SRDB that have citation.ID imported as "NAC" (418 cases) are that way because their _Quality_flag_ is "Q02" in the original SRDB data base.

@teixeirak , please close this issue if that is what is supposed to be.

**Comment by teixeirak** [comment]
For the record, Q02 = data from another study.

This is correct according to my original instructions, but I'm wondering if it would be better to somehow retain the citation in SRDB in association with these records-- at least in source.notes. @bpbond, do you have an opinion on this? Would the citations associated with records with this code typically at least point to the real source? It seems important to preserve those citations.  Maybe list the study in citation.ID and then put a note in source.notes that data may be from other study?

**Comment by bpbond** [comment]
Usually the "Q02" codes aren't that important; it signals that some of the ancillary data, not the primary soil respiration data, come from another study.

**Comment by teixeirak** [comment]
Okay, @ValentineHerr , let's include the citation.ID for these studies, but add a note in `source.notes` on variables other than soil respiration stating that data may come from another study.

**Comment by ValentineHerr** [comment]
Ok, now all records for variables other than  "R_soil_C", "R_het_litter_C", "R_auto_root_C", "R_het_soil_C", "R_auto_root_C" or "R_het_soil_C" get "**Non-soil respiration data may come from another study**." added to their _source.notes_ field if their quality flag was originally "Q02" in SRDB.

@teixeirak, please close if that is correct.

**Comment by teixeirak** [comment]
Good, thanks!
