### ISSUE TITLE
SRDB _dominant.veg_ gives biomes of type  "Boreal **Other** MATURE" and are not counted in numbers and facts

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#187]
@teixeirak ,

I worked through the fixes with SRDB import but the C cycle diagrams and other figures have still not changed.

I found out why:
The _dominant.veg_ of new SRDB records are 2TD, 2TE, 2TM or NAC and those are all classified as "others" in the leaf traits as they are neither broadleaf (2TEB, 2TDB or 2TB) nor conifers (2TEN, 2TDN, 2TN).
that means that the biomes for SRDB records are of type  "Boreal **Other** MATURE" , "Temperate Other YOUNG" etc...     and those biomes are not of interests (as opposed to "Tropical broadleaf MATURE" or "Boreal conifer YOUNG", etc...) in the code so they are not counted in the different outputs of numbers and facts or figures...

let me know how you want to deal with that.

**Comment by teixeirak** [comment]
Unfortunately, I don't see an easy way to totally automate this from SRDB, as there is no field indicating broadleaf/ needleleaf. However, we can apply some rules to get a lot of them (I'll start this list now and add some more in edits):

-[ ] if dominant.veg = 2TE and | latitude | > 40, assign 2TEN.

**Comment by ValentineHerr** [comment]
@teixeirak ,
I ended up scraping the full list of Angiosperms and Gymnosperms to have a complete list of genus.

Question:
 - After doing item 1 above, when I find cases to replace in item 3, I have 2TD, 2TE, 2TEN. I am assuming that I should replace:
    -  2TD by 2TDN
    -  2TE by 2TEN
    - 2TEN by 2TEN
    - if some other ones show up I would replace them by 2TN

Right?

same with broadleaf ? cases I have are 2TD, 2TE and NAC, so i would replace
   - 2TD by 2TDB
   - 2TE by 2TEB
   - NAC by 2TB


correct?

**Comment by teixeirak** [comment]
Correct.

**Comment by ValentineHerr** [comment]
Success!!!
Figures have many more records in them now.!!!
I'll wait a little before I push everything. I still need to double check all the stuff mentioned in issues that I likely fixed before vacation but never double checked.
@teixeirak, I pushed the new_data [here ](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/srdb/new_data)if you want to have a look at it.

**Comment by teixeirak** [comment]
Great! I'm looking forward to seeing them! I'll try to make it through some of these issues now. (I've been out with Yannik doing some June sledding and hiking in the Sierras!)
