### ISSUE TITLE
duplicated records and measurement.ID

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#188]
@beckybanbury , I am noticing that some records you entered appear several times (see measurement.ID 17613-17648 and 17638-17641).
It is not a big deal for the analysis because the code IDs them as replicates and averages them out but it would be nice to delete the replicate ones so that we don't over estimate the number of data we have in ForC and, most importantly, we can spot cases where the measurements are not replicates but are true problems (have the same ID but are actually different).

@teixeirak, I think there is measurement.ID issue with ID 4343, it is duplicated, once for Duke Forest Loblolly Pine and once for Mt. Disappointment. Maria entered that data. Do you know what happened?

**Comment by ValentineHerr** [comment]
For Information,
This is an important issue as the second record with same measurement.ID will be lost in the script that IDs duplicated records (the uses measurement.ID to match things up, when there is a tie it uses first match only and the second is lost).

I am adding a check in QA/QC script. to flag when there is duplicate measurement.ID

I am giving a new measurement.ID to Duke Forest Loblolly Pine.

**Comment by beckybanbury** [comment]
@ValentineHerr wow that's super weird, I have no idea how that happened; I'll delete them and let me know if you find any others!

**Comment by ValentineHerr** [comment]
I know it is strange. I hope it is not a symptom of something wrong in a script.
Let me know when you are done with it.

**Comment by teixeirak** [comment]
regarding record 4343, it was only associated to Duke Forest in the Ecology data pub. Mt. Dissapointment had IDs 9864-9869.

**Comment by teixeirak** [comment]
(Oh, looks like you already figured that out!)
