### ISSUE TITLE
pull request for SRDB

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#189]
@teixeirak ,

I created a new branch called "with_SRDB".

Everything is updated in there (including C cycle diagrams), except range of variables in metadata (I think they are a few outliers to double check).

We can use it to do a final pass to double check everything and then do a pull request.

**Comment by teixeirak** [comment]
Okay. Do you recommend doing any hand edits before or after merging?

**Comment by ValentineHerr** [comment]
I updated the "with_SRDB" branch.
@teixeirak it is probably best to wait a couple days before doing the pull request, to leave time to double check things. let me know if you see anything bad.

I don't know what is best for the hand edits... I don't like having 2 branches for 2 long so probably best to do them after we merge?

**Comment by teixeirak** [comment]
I've reviewed and the only issue I found is the continued presence of "mature" in plot names. Once that is fixed, I think we can go ahead and merge.
