### ISSUE TITLE
SRDB import: SRDB records are missing in ForC import

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#192]
@ValentineHerr , what happened to SRDB record numbers 15-21 (Wang study)? I don't see them in our import. (I was looking for them in relation to issue #191 ).

**Comment by ValentineHerr** [comment]
Good catch. I had to remove cases where RC_annual and Rs_annual were not both there but I did not handled it correctly and it deleted the whole rows.
I'll fix that.

**Comment by teixeirak** [comment]
Would the same apply to Harwood forest (Zerva_2005_seoc)? I noticed missing recrods for that one as well.

**Comment by ValentineHerr** [comment]
Yes it does.
they are back now (have not pushed changes yet, still waiting until we figure out dome of the other things)

**Comment by teixeirak** [comment]
@ValentineHerr, I'm not sure this got completely solved. Records from Oishi_2013_satv (5461-5478; Rs_annual) seem to be missing. 

Zerva_2005_seoc also seems to be still missing the Rs_annual.

**Comment by ValentineHerr** [comment]
Indeed... I did not import those Rs_annual because they were not paired with RC_annual...
But this should only apply to RC_annual: RC_annual should not be imported if it is not paired with Rs_annual...
Rs_annual can stand alone...
I'll import the extra records.

**Comment by ValentineHerr** [comment]
@teixeirak I added the extra R_Soil_C data and updated all ForC and ForC_simplified files. (see[ this commit](https://github.com/forc-db/ForC/commit/ca04b293f69936a3e8fa87aa191482cbfe91aaa2))

I reviewed most of the duplicates that needed manual D.precedence but there are a few from Oishi_2013_satv that I think require your attention.

**Comment by teixeirak** [comment]
That added about 3,000 records and definitely beefed up our soil respiration data! 
![image](https://user-images.githubusercontent.com/6355854/59636767-599eb680-9122-11e9-90b8-e550a7b62c40.png)

**Comment by bpbond** [comment]
Awesome! 🎉
