### ISSUE TITLE
SRDB merge: mismatch between dominant.veg and veg.notes

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#193]
@beckybanbury,
I'm noting a mismatch between dominant.veg and veg.notes for some of the records in SRDB. Fore example, BOREAS NSA-D1995 (measurement.ID 20484) is listed as 2TD with species Picea mariana; Pinus banksiana; Populus tremuloides. Based on these species, it should be 2TM.
Could you please scan some more to see how pervasive this problem is? Please check the original SRDB data (field indicating deciduous/ evergreen). Try to determine whether this is a single error or a problem with the code. You may also consult with @ValentineHerr.
This relates to issue #187.

**Comment by ValentineHerr** [comment]
I can answer for that particular example quickly.
It correspond to 2nd record in SRDB. Its leaf_habit is "Deciduous" and the script generates "2TD".

**Comment by teixeirak** [comment]
We have determined that these are errors in SRDB, and @beckybanbury is recording a list of plots requiring a fix in issue #181 .

**Comment by teixeirak** [comment]
I will close this now because it is not a code issue.
