### ISSUE TITLE
SRDB import: mature still shows up in plot names

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#195]
@ValentineHerr, unfortunately, I just noticed that "mature" still shows up in the plot names of stands with age = NAC, which I think is something that will need to be fixed in the import code.  If its easier, we can just delete all instances of "mature". Sorry I didn't catch that earlier.

I made only a couple small edits (deleted two records) since the merge of the new version, so I don't think we'd be losing much if we just revert. It looks like @beckybanbury pulled in climate data, so we'll want to preserve that.

**Comment by teixeirak** [comment]
It's probably easier to just search for and remove  "mature" from SRDB plot names? I don't mind losing it from the forests with stand age>100.

**Comment by teixeirak** [comment]
Nevermind, I fixed it manually.

**Comment by ValentineHerr** [comment]
Ok thanks for doing it. Sorry I left the mature for stand "NAC", I thought you had see this message: https://github.com/forc-db/ForC/issues/178#issuecomment-502136259

**Comment by teixeirak** [comment]
Oops, I wasn’t paying enough attention. Sorry about that!
