### ISSUE TITLE
site name "S" refers to both a site in Malaysia and a site in Spain (SRDB)

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#196]
I noticed that there is a site name in SRDB that is used for a site in Malaysia and a site in Spain.

The site is called "S".
The site info for the Spain site has not been imported (because the sitename already existed after imported the Malaysian site).

The Spain site info is in **SRDB,  record ID 4810.**

So we need to:

- [ ] change the sitename of the Spain record in MEASUREMENTS
- [ ] add a site record for it in SITES
- [ ] check the History of that site in HISTORY and add it if needed. (change the site name there too)
- [ ] update PLOTS by running the script
- [ ] run all scripts that need to run when there is a change in the data... but that can happen later.

**Comment by teixeirak** [comment]
Don't bother. Method = soda lime, so it wouldn't get used in analyses anyway, and the only other variable measured is soil C.
