### ISSUE TITLE
confirm that code handles stand-clearing disturbance correctly.

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#200]
`Teshio Experimental Forest` | `CC-LaG experiment site (TSE)` experienced a stand-clearing disturbance and had age reset from 999 to 0.  I just fixed/merged plots for this site.

@ValentineHerr, its possible that this plot could "break" the code (or not be handled correctly). When you have a chance, I'd like to check that. (This should be as simple as checking output after running plots code.)

**Comment by ValentineHerr** [comment]
the plot code did not break and I believe it handle the situation correctly (@teixeirak, you can check once I push big update after integrating GROA data)

**Comment by teixeirak** [comment]
Looks good.
