### ISSUE TITLE
ID_sets_of_duplicate_records

### ISSUE THREAD

**Issue by beckybanbury** [forc-db/ForC#201]
Now that some of the duplicate sites are corrected, we need to run the code ID_sets_of_duplicate_records. When I run this code, it is randomly replacing a lot of rows of data with all NAs (removing all the data in the row). The number of rows is the same in the new file to the old file, so it isn’t adding rows of NAs. The code appears to be running okay and without errors.

Do you have any ideas about what could be causing this problem?

@teixeirak @ValentineHerr

**Comment by ValentineHerr** [comment]
Hmmm...
not sure what is happening.
Becky, you could try to break the big loop by adding an if statement at the end of it (before the list slot gets overwritten), something like
If(any(is.na(X$record_ID))) stop(print(i))
May need to adapt  names accordingly. I do not have the code in front of me right now.
Once the loop breaks it will print what loop index it is at and you can try to run the inside of the loop step by step with that loop index to see what happens and when the NA get generated....

Hope that helps for now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by beckybanbury** [comment]
Thanks so much - I'll try that!

**Comment by ValentineHerr** [comment]
@beckybanbury, did you manage to fix the issue?

**Comment by ValentineHerr** [comment]
Closing fixing the duplicated measurements ID (#203) fixed this issue.

note: issue #204 needs to be fixed before we can update ForC_simplified

**Comment by ValentineHerr** [comment]
I updated ForC and ForC_simplified after #204 was closed.
