### ISSUE TITLE
fix some duplicated measurement.ID

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#203]
@teixeirak,
I believe you might have duplicated some measurements.ID in [this commit](https://github.com/forc-db/ForC/commit/a2e4f3a23bb2666644db4e07a5c322ab75095e4b#diff-756d8a2976127b356488fcc5778dd5af): 
 - 28513: already existed for Harvard Forest-Prospect Hill-WD1, 
 - 28514: you entered 2 entries with that ID, and 
 - 28515: already existed for 	Harvard Forest-Prospect Hill-MD1). 

This might be why the duplicated code is not working (see [this issue](https://github.com/forc-db/ForC/issues/201#issuecomment-519135259))
Can you have a look and see if you can easily fix that easily?

**Comment by teixeirak** [comment]
Should be fixed!

**Comment by ValentineHerr** [comment]
thanks!
