### ISSUE TITLE
Add history to some plots

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#204]
We are missing some history records...
They must have been lost somewhere along the way because I don't remember having this issue before... They all are from SRDB measurements and I feel that I would have noticed that they were missing before. I fixed a couple that occurred when some records had their plot name updated but others from the same plots were missed. 

I can't find why the history of the ones in the table below disappeared.

@teixeirak or @beckybanbury, do you remember changing something about these? If not, hopefully I just missed that before (otherwise there is something somewhere that is deleting data...)

 
sites.sitename | plot.name | notes for this issue
-- | -- | --
Takayama   Experimental Field Station | Temperate Deciduous Forest | There is a history record for plot.name "Temperate Deciduous   Forest. Stand established around 1954
Stillberg | Temperate Mixed Forest. Stand established   around 1975
Stillberg | Managed Temperate Mixed Forest with CO2 (575 ppm) treatment. Stand   established around 1975
Skogaryd | Boreal Evergreen Forest. Stand established   around 1951
Skogaryd | Boreal Evergreen Forest with Fertilization   (3.3 t/ha) treatment. Stand established around 1951
Skogaryd | Boreal Evergreen Forest with Fertilization   (5.5 t/ha) treatment. Stand established around 1951
Sambong Exhibition   Forests | Temperate Deciduous Forest. Stand   established around 1966
Pumpanen_2004_scef   research site in Finland | Boreal Evergreen Forest. Stand established   around 1867
Oak Ridge | Managed Aggrading Temperate Deciduous   Forest with CO2 (528 ppm) treatment. Stand established around 1987
Oak Ridge | Managed Aggrading Temperate Deciduous Forest with CO2 (538 ppm)   treatment. Stand established around 1987
Oak Ridge | Managed Aggrading Temperate Deciduous Forest with CO2 (545 ppm)   treatment. Stand established around 1987
Oak Ridge | Managed Aggrading Temperate Deciduous Forest with CO2 (548 ppm)   treatment. Stand established around 1987
Nara | Temperate Deciduous Forest
Nara | Temperate Evergreen Forest
Morgan-Monroe State   Forest | Temperate Deciduous Forest
Fuchu | Managed
FACTS-I | Managed Aggrading Temperate Evergreen   Forest with CO2 (574 ppm) treatment. Stand established around 1983
Dinghushan Biosphere Reserve | Tropical Evergreen Forest. Stand established around 1604
Dinghushan Biosphere Reserve | Tropical Evergreen Forest with Fertilized (5 gN/m2/yr) treatment. Stand established around 1604
Dinghushan Biosphere Reserve | Tropical Evergreen Forest with Fertilized (10 gN/m2/yr) treatment. Stand established around 1604
Dinghushan Biosphere Reserve | Tropical Evergreen Forest with Fertilized (15 gN/m2/yr) treatment. Stand established around 1604
Dinghushan Biosphere Reserve | Subtropical Evergreen Forest with Drought treatment. Stand established around 1604
Dinghushan Biosphere Reserve | Subtropical Evergreen Forest with Double precipitation treatment. Stand established around 1604
Dinghushan Biosphere Reserve | Subtropical Deciduous Forest. Stand established around 1924
Dinghushan Biosphere Reserve | Subtropical Deciduous Forest. Stand established around 1934
Beyer_1991_icav   research site in Schleswig-Holstein Germany | Temperate Deciduous Forest

**Comment by ValentineHerr** [comment]
Nara is also missing an entry in SITES

**Comment by teixeirak** [comment]
I'm not sure what happened. I suspect that at least some of these came in when I was making some corrections to the imported data. Nara was an instance where I apparently didn't finish changing site/plot names in measurements. 

I hope I didn't manage to introduce that many mistakes!

**Comment by teixeirak** [comment]
I will try to look at this more soon.

**Comment by teixeirak** [comment]
@beckybanbury, do you remember modifying any of these site/plot names?

**Comment by beckybanbury** [comment]
I've just checked my history of commits to ForC history and I haven't edited any of these. The last edit I made was June 24th!

**Comment by teixeirak** [comment]
Here's my running list of what needs to be done to solve these. @beckybanbury, it would be great to get your help with ones where you'd feel comfortable:

- [ ] Takayama has 5 sites that are probably all duplicates (now coded supersite "Takayama"). `Takayama Research   Station | Temperate Deciduous Forest` is the one that is missing plot info. While we're at it, we might as well review/ merge.

**Comment by teixeirak** [comment]
So far, there seems to be a different problem with each (and I’m not always sure of the cause)—e.g., duplicate plots (sometimes sites) that need to be merged, problematic site names (e.g., mixing deciduous/evergreen or boreal/temperate). I've found that the best process is to pull up records for the site/plot in SITES, HISTORY, and MEASUREMENTS. Check for obvious duplicates and discrepancies with species, leaf type, etc. The problem has always been clear to me just from looking at these, and in most cases I've needed to reference the original publication to determine which record is correct (although sometimes its obvious-- e.g., if plot name doesn't match the species/ dominant vegetation). Generally, merging duplicate plots (usually where one is incorrect) has solved the problem. 
@beckybanbury, it would be great to get your help with this.

**Comment by beckybanbury** [comment]
@teixeirak Morgan Monroe State Forest seems to be a duplicate site - should I go on with removing duplicates I find?

**Comment by beckybanbury** [comment]
@teixeirak row 9383 in the history table has no history.ID or sitename - I think it's Skorgaryd but I don't want to edit that row without knowing what you were referring to!

**Comment by teixeirak** [comment]
> @teixeirak Morgan Monroe State Forest seems to be a duplicate site - should I go on with removing duplicates I find?

Yes, please do.

**Comment by teixeirak** [comment]
> @teixeirak row 9383 in the history table has no history.ID or sitename - I think it's Skorgaryd but I don't want to edit that row without knowing what you were referring to!

That's correct. Could you please fill it in so we don't create conflicted copies? 
Thanks for catching it!

**Comment by teixeirak** [comment]
I believe these are all resolved (ugh, Dinghushan was a mess!). We will need to run the scripts (checks  duplicates, etc.) -- @ValentineHerr , @beckybanbury

**Comment by ValentineHerr** [comment]
@teixeirak it looks like Dinghushan 7 (only one plot: broadleaf forest monsoon evergreen broadleaf forest (MEBF)) is still missing a history record.

**Comment by teixeirak** [comment]
Thanks for checking! This is fixed (forgot to change the site/plot name on that record).

**Comment by ValentineHerr** [comment]
perfect, thanks!
