### ISSUE TITLE
Add Regentype and Managementtype codes 

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#21]
@ValentineHerr, ForC does not currently contain Regentype and Managementtype (Measurements file) for extratropical sites. I have found a [file where Maria had added these codes](https://github.com/forc-db/ForC_private/blob/master/archived%20database%20versions/ForC_2016-02/ForC_measurements_lifeform.csv). Could you please merge these into the master? (I'm assuming this will be easy. If not, please alert me.)

**Comment by ValentineHerr** [comment]
@teixeirak, It looks like some sites.sitename or plot.names have changed since Maria's version.
I am able to fix all of them but one: in public version, record of site.sitename ="Honghuaerji" and plot.name = "birch stand_age55" for stand.age is 81. So I am not sure how to handle that one. The only [sitename plotname] we have in maria's version is "Honghuaerji Pinus sylvestris var. mongolica"
Let me know what to do for that and I should be able to move forward.

**Comment by teixeirak** [comment]
I located and fixed the problem in ForC_measurements (just pushed the fixed file).

**Comment by teixeirak** [comment]
Resolved here: https://github.com/forc-db/ForC/pull/24.

**Comment by teixeirak** [comment]
Upon some more review, there actually seem to be quite a few errors in these two fields, including some inconsistencies with the earlier version(s) (for example, cocoflux). @ValentineHerr, could you please see if you can figure out what happened? I did do some editing by hand, so best to go back to the first version you created. 
If this is too difficult to sort out, it might make sense to simply remove them. Let's discuss tomorrow.

**Comment by teixeirak** [comment]
Upon further thought, because these two fields were primarily generated by code (and fixed by hand), in order to make them transparent/ reproducible, its probably better to remove them or provide code (Maria's or new) to generate them.

**Comment by teixeirak** [comment]
I deleted these fields for two reasons:
1-They appeared to have become corrupted. 
2- These two fields were primarily generated by code (and fixed by hand). In order to make them transparent and reproducible, it would be better to provide code to generate them.

I think it would be great to reinstate these or similar fields, and this should not be difficult as we now have the PLOTS file and previous files to go back to and can recover these fields from previous database version (for sites/plots that do not undergo name change).
