### ISSUE TITLE
Missing a citation

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#214]
@teixeirak, citation Olson_2013_nmna does not appear in CITATIONS but exists in MEASUREMENTS. Do you know where it went/what it is?

At one measurement has this in the citation.ID: "Leigh_1999_tfea; Foster_1982_fobc"
Which makes it hard to match. any suggestion on how to handle that?

**Comment by teixeirak** [comment]
I fixed both of these.
