### ISSUE TITLE
Confidence intervals

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#215]
@teixeirak,
The measurements with "95%CI" in `stat.name` don't have 2 values in `stat`. Am I missing something about how to retrieve the CI or is something not right?

**Comment by ValentineHerr** [comment]
Also there is quite a few stats (95%CI or SE) that have n = 1.

**Comment by teixeirak** [comment]
> @teixeirak,
> 
> The measurements with "95%CI" in `stat.name` don't have 2 values in `stat`. Am I missing something about how to retrieve the CI or is something not right?
> 
>  

The database structure assumes symmetrical 95%CIs, and if its not symmetrical, that would be in the notes. Perhaps something that should be fixed, and could probably be done fairly easily. The values entered should be distance from mean.

**Comment by teixeirak** [comment]
> Also there is quite a few stats (95%CI or SE) that have n = 1.

The ones I'm aware of are ForestGEO plots, with 95% CIs calculated by bootstrapping across quadrats. So, those are fine.

**Comment by ValentineHerr** [comment]
> > Also there is quite a few stats (95%CI or SE) that have n = 1.
> 
> The ones I'm aware of are ForestGEO plots, with 95% CIs calculated by bootstrapping across quadrats. So, those are fine.

Ok, I'll add the notes so that they have this info... (but I feel than n should be the number of quadrats)

**Comment by teixeirak** [comment]
Hmmm... looks like we have a problem with some of those 95%CIs. I think some were entered as difference from the mean (e.g., Meakem_2017_rots), and others as the raw value (e.g., Chave_2008_aepa). Fortunately it's not a lot of records to review.

**Comment by teixeirak** [comment]
Perhaps it makes more sense to restructure with n, SD, SE, and lower 95% CI, and upper 95% CI. Drop the stat.name column. What do you think?
