### ISSUE TITLE
Check for and correct any records where different-aged stands are identified by a single plot

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#22]
@ValentineHerr,  

There may be some records where stands of different age have the same site and plot name. As every plot should be differentiated based on the site and plot names only, this would be incorrect. 
Note, however, that when the same plot is repeatedly measured, site and plot name should stay the same while stand age changes. * Problematic records would be those with the same site name, plot name, and measurement date but different ages.*  There may be some where the measurement date is unknown, in which case this can't be assessed. Let's assess whether the problem exists.

If we do find cases where this occurs, could you please redo all of those plot names by adding '_age##' to the end of the current name?

For example (note that this example is a case that might not be wrong--measurement date not acquired):

Site | Plot | Age
--- | --- | ---
Honghuaerji | Pinus sylvestris var. mongolica | 81
Honghuaerji | Pinus sylvestris var. mongolica | 86

becomes:

Site | Plot | Age
--- | --- | ---
Honghuaerji | Pinus sylvestris var. mongolica_age81 | 81
Honghuaerji | Pinus sylvestris var. mongolica_age86 | 86

We'll need to add any new plots to ForC_history (and from there ForC_plots). If you confirm that there are some plots with this problem, please generate records for ForC_history as follows:

historyID | sites.sitename | plot.name | plotarea | event.sequence | date | dateloc | distcat | disttype | level | units | percent.mortality | distnotes | plothistoryID.v1 | tropical_extratropical
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
NA | Honghuaerji | Pinus sylvestris var. mongolica_age81 | NAC | 1 | NAC | 9 | No.Info | NAC | NA | NA | NA | NA | NA | extratropical

I will then compare with existing records and either merge by hand or provide instructions for merging via script.

**Comment by teixeirak** [comment]
Fortunately, I found that this issue was not present in the database (in any significant way). There were (and still are) some instances where there are multiple ages listed for a plot for the same measurement year. Reasons for this include:
1- A discrepancy in age reported by different studies reporting on the same site. These are usually relatively small differences. I have retained the ages as reported in association with the measurements. 
2-  A slight (e.g., 1 yr) inconsistency between measurement date and stand age, which is most likely due to imprecision in the measurement date.
3- Mismatch between ages given in plot names (presumably based on description in paper) and those digitized from plots. Again, mismatch is typically small.  

In the end, the changes introduced by [our script](https://github.com/forc-db/ForC/blob/master/scripts/archive/R_ForC_Check%20for%20and%20correct%20any%20records%20where%20different-aged%20stands%20are%20identified%20by%20a%20single%20plot.R) were all rejected when it comes to using them to identify plots that need to be split. However, it does point to (some of the) records that contain the slight discrepancies identified above.

**Comment by bpbond** [comment]
So should the qc script ( #23 ) check for this issue?

**Comment by teixeirak** [comment]
I'm satisfied that there are no plots that need to be split because multiple stands of different age were represented by the same plot.

However, it would probably be useful (although not super high priority) for the qc script to identify inconsistencies in stand age & measurement date within plots. For example, if the stand was 20 years old in 1990, it should be 21 in 1991. I suspect that there will be a lot of small (i.e., 1 year) discrepancies, and I wouldn't be so concerned about those.  Obviously the larger the discrepancy, the more concerning, so it would be valuable to list the size of the discrepancy.
