### ISSUE TITLE
Update citations and reference library

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#223]
I'm opening this issue for the record, and to update @ValentineHerr.

@Troger4 is currently working on updating [ForC_citations](https://github.com/forc-db/ForC/blob/master/data/ForC_citations.csv) and the [reference library](https://github.com/forc-db/References). Tasks include the following (@Troger4 , you can check these off once you're done):

- [ ] look up missing DOIs ("NAC" in doi field), putting "NA" if it's a book and skipping any that are problematic
- [ ] if reference is a book, fill in citation URL and abstract (if easy)
- [x] fill in language inn cases where citation.language is "NAC" and citation.citation is NOT "NAC". 
- [ ] save pdf with citation.ID as file name, if it doesn't exist in our References repository
- [ ] if pdf does exist in our references repository, rename with citation.ID
- [ ] mark a "1" in `pdf.in.repository` if the pdf is in References repository

@Troger4 , this is your first example of a GitHub issue. If you run into any questions related to this, it will be best if you post them in the issue (online or by responding to email). That way, we'll retain a record of what we've worked through/ decided.

**Comment by teixeirak** [comment]
@Troger4 , I forgot to mention that a lot of citations are available here: https://www.dropbox.com/sh/znee1tak8t7zu6o/AAA-poV8sBLKvAPdIDBC4B0ga?dl=0 . These are references from another database (SRDB) that we imported. I don't know if this will be helpful at this point. SRDB records all have DOIs (when applicable), so this will be different from the set you're looking up.

**Comment by teixeirak** [comment]
@Troger4 ,

It would be great if you could make sure all of the following pubs have complete records (they probably do):
 
- [ ] Archibald_2009_doiv
- [ ] Chave_2008_aepa
- [ ] Goulden_1996_eocd
- [ ] Keith_2009_mmce
- [ ] Keller_2001_beit
- [ ] Lin_2012_tvia
- [ ] Meakem_2017_rots
- [ ] Ngo_2013_csip
- [ ] Orihuela-Belmonte_2013_csaa
- [ ] Rice_2004_cbav
- [ ] Saleska_2003_ciaf
- [ ] Toky_1983_ssfs
- [ ] Uhl_1984_sand

These are studies likely to go to IPCC in the first round.

**Comment by Troger4** [comment]
I checked all the publications and added in a few abstracts. I also added in all of the "NACs" in the language column. I didn't see the last part of your message till now so I did add language for NAC citation.citation but I do not believe it was many and all of the remaining publications in this category had language already filled. Very sorry for the confusion.

**Comment by teixeirak** [comment]
Many thanks, @Troger4, and no worries about adding language when citation.citation=NAC. This won't mess anything up.

**Comment by teixeirak** [comment]
@Troger4 , @ValentineHerr , I realized that our method of getting language isn't fool-proof in that there are some studies with titles and abstracts translated into English. I know we have a few original studies in Mandarin and maybe other languages where this is the case (I found and corrected one: Yu_1999_doae). I don't see a way to resolve this short of accessing the original pdfs, which of course we'll do for any that we send to IPCC.  Teagan, as you go through and retrieve/ rename pdfs, you may find these and can correct the entries.

**Comment by ValentineHerr** [comment]
Thanks for fixing this @teixeirak. 
Yes, it can be tricky... also, IPPC wants the abstracts in English, regardless, so @Troger4, when you see an abstract in something other than the English, please edit to replace with the English abstract that is usually in the PDF (or online). Thanks!

**Comment by Troger4** [comment]
Thanks for letting me know! I’ll work on accessing the original documents to double check as I go through the list. If the study only has a summary and not an abstract, would you like me to use a summary in the same capacity?

Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ValentineHerr** [comment]
Yes, if there is only a summary you can enter that, thanks!

Valentine Herrmann
________________________________
Research Assistant
Smithsonian Institution
Smithsonian Conservation Biology Institute
1500 Remount Rd.; Front Royal, VA 22630 USA
1-540-635-6549 | ***@***.***

________________________________

**Comment by Troger4** [comment]
Will do. I'll also keep a record of deleted duplicates.

**Comment by teixeirak** [comment]
I think we need a little more clarification here:
- if there is an exact duplicate (same code, author, year, title), go ahead and delete. I don't see any need to track it so long as you're confident that it's really a duplicate, as opposed to--for example-- same author_year, but different title.
- if there's something where author/ year/ DOI are all the same but the code is different, put that in a list and Valentine or I can determine which code is correct. Please don't delete any of those records or change anything in the other files for now. 
- also (unlikely), in case there are two with the same code but different full title, alert us (this would be a problem with our system)

**Comment by Troger4** [comment]
I haven't come across any citation.IDs that I have needed to change in citations, I have been renaming the pdf records in references to match the citation.ID in the citations doc. 
Thank you for the clarification!

**Comment by ValentineHerr** [comment]
@Troger4 and @teixeirak,  something went wrong with the CITATIONS. Looks like a merging issue. one of you needs to decide what version to keep.

**Comment by teixeirak** [comment]
@Troger4 , could we do a quick zoom call to resolve this?

**Comment by teixeirak** [comment]
Alternatively (and easier), @Troger4 , you can let me know when you're not working on the file and I can fix it (then you'll just need to be sure to pull again before editing).

**Comment by Troger4** [comment]
Sorry I am just now seeing these. I'll be sure to save more as I go to prevent these issues. Could you show me how to deal with merging issues tomorrow during our Zoom meeting? Thank you!

**Comment by teixeirak** [comment]
@ValentineHerr , a couple questions following my discussion with @Troger4 this AM:

1- will it mess things up if there are return characters within the abstract?
2- Is it useful to retrieve URL and abstract if there's a DOI but those fields remain blank (i.e., does your lookup process fail on some refs)?

**Comment by ValentineHerr** [comment]
> 1- will it mess things up if there are return characters within the abstract?

If it is carriage return `\r` and not new line return `\n` it should not mess things up.


> Is it useful to retrieve URL and abstract if there's a DOI but those fields remain blank (i.e., does your lookup process fail on some refs)?

If there is a DOI but no URL, that means my look up process (using http://doi.org/[DOI]) failed to find the URL. So if you can retrieve a working URL while you are looking for the complete citation and language (require by IPCC), it would be great. URL is not require for the IPCC import but having it could be useful if we want to retrieve something else in the future. For the abstracts, they are also not required by IPCC and they are more of a pain (special characters, huge etc....) so either way is fine.

**Comment by ValentineHerr** [comment]
so it looks like maybe there has been a `\n`.... because some data got moved down. e.g. the info about Meakem_2017_rots is not the line below...
I can't figure out what commit caused that. I'll try to find out....

**Comment by teixeirak** [comment]
I think there may be more than one. Those would be commits from yesterday. Teagan now knows to avoid.

**Comment by teixeirak** [comment]
@Troger4 , it turns out that the returns in the abstracts were not causing the problem. Valentine found and fixed-- please see messages on Teams, and be sure to pull the latest version and work from that one.

**Comment by Troger4** [comment]
Will do, thank you!

**Comment by teixeirak** [comment]
@Troger4 , could you please prioritize the following:

- [ ] Brown_1989_bemf
- [ ] Brown_1997_ebab
- [ ] Weaver_1992_tbef
- [ ] Ovington_1970_bacc
- [ ] Crow_1980_arca
- [ ] Niiyama_2010_eorb
- [ ] Kenzo_2009_doar
- [ ] Ker_1980_tbef
- [ ] Ker_1984_befs

**Comment by Troger4** [comment]
Yes, I'll start on these now.

**Comment by Troger4** [comment]
I see some of these already have DOIs, would you like me to manually fill in the other field info?

**Comment by teixeirak** [comment]
I think they should be fine if they have DOIs. (Maybe those are the DOIs you've added since Valentine pulled the info? )@ValentineHerr , do you agree?

**Comment by ValentineHerr** [comment]
Well, my script ignores when there is no full citation or language because those are required by IPCC, so it would be great to add.

**Comment by ValentineHerr** [comment]
these are for allometries so I could change my script to keep those but that would mean not giving full citation but just DOI for the biomass allometry slot.

**Comment by teixeirak** [comment]
I think we have some confusion here. What I meant above was that if Teagan adds the DOI, you should be able to pull the other info, correct?

I think it's fine to just give the DOI if the full citation is not available, but shouldn't be necessary.

**Comment by ValentineHerr** [comment]
Oh... sorry I see the confusion, my bad. I was not planning on re-running that code that pulls the rest of the info as I thought that subsequent manual lookups might as well fill in the info which would for sure be accurate.

**Comment by ValentineHerr** [comment]
And, if there is already a DOI that means my code was not able to pull any info.

**Comment by teixeirak** [comment]
> Oh... sorry I see the confusion, my bad. I was not planning on re-running that code that pulls the rest of the info as I thought that subsequent manual lookups might as well fill in the info which would for sure be accurate.

Hmmm... I think we should do this, at least for the subset with DOI and lacking the other info.  None of the references from GROA came with DOIs, so that's a lot of studies. I asked @Troger4 to just put the DOI.

**Comment by teixeirak** [comment]
If the lookup failed, that would be something to fill in eventually, but I've asked Teagan to move through these quickly and just pull missing DOIs, with lower priority for the other info. The ones with missing info may tend to be tricky, and I figured we could pull those later as needed.

**Comment by ValentineHerr** [comment]
Ok, I'll re-run that script when there is a substential number of new DOIs. (maybe it is already the case?)

**Comment by Troger4** [comment]
I'll try to get as many DOI as I can tomorrow and we can rerun Sunday or Monday before the deadline. For these pubs, Brown_1997_ebab is a book and doesn't have an abstract so I put NA. I wasn't able to find Ovington_1970_bacc through google scholars or George Mason Library. Kenzo_2009_doar,    Ker_1980_tbef,   Ker_1984_befs,   are not in the CITATIONS document.

**Comment by teixeirak** [comment]
Thanks, @Troger4 . I don't think any of these are limiting us in terms of what we submit for this first deadline, and we probably won't send them anything past today (because of the weekend, and their Monday starts our Sunday evening).

**Comment by teixeirak** [comment]
I started a list of missing citations in issue #228 .

**Comment by Troger4** [comment]
Great, thank you.

**Comment by Troger4** [comment]
Hi there! I found a CITATION with the first name as the citation.ID instead of last name. Creighton_2004_eotd should be Litton_2004_eotd.

**Comment by teixeirak** [comment]
> Hi there! I found a CITATION with the first name as the citation.ID instead of last name. Creighton_2004_eotd should be Litton_2004_eotd.

Thanks, @Troger4 !  I've fixed that in the other files. Please delete Creighton_2004_eotd from the citations spreadsheet and give the pdf the correct name.

**Comment by Troger4** [comment]
Will do! Thank you.

**Comment by teixeirak** [comment]
@ValentineHerr , @Troger4 has finished filling in the missing DOIs, when feasible. You can now re-run the info look-up script for those references.

**Comment by ValentineHerr** [comment]
looks like there still may be some merging issues with CITATIONS.

![image](https://user-images.githubusercontent.com/19673377/115042998-045c9900-9ea2-11eb-9c85-4ec9906f970f.png)

**Comment by teixeirak** [comment]
I'll check into it.

**Comment by ValentineHerr** [comment]
I added what the script was able to retrieve (forgot to refer to this issue in the commits).

**Comment by teixeirak** [comment]
Okay, thanks. I'll close this issue now. We can retrieve missing info on an as-needed basis.

@Troger4 , many thanks for all your help!

**Comment by Troger4** [comment]
Of course! Thank you for teaching me how it all works!
