### ISSUE TITLE
Site coordinates

### ISSUE THREAD

**Issue by beckybanbury** [forc-db/ForC#233]
@teixeirak In extracting the worldclim data, it seems that there's a few sites with co-ordinates that worldclim doesn't have data for - a quick look suggests that it's because the co-ordinates are actually in the ocean. Would it be worth checking through these? It's easy to find the sites as they're the ones without worldclim values in the extracted datasheet. (This is probably also relevant to issue #229 )

**Comment by teixeirak** [comment]
Thanks for catching this. Yes, for those records, please fill the `coordinates.precision` field in sites with "suspect".
