### ISSUE TITLE
re-run statistics on variables

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#235]
@ValentineHerr , when you have a chance, assuming it's fast, could you please run your script for updating the data in the variables spreadsheet (n records, min, max). This will be for @Troger4's final presentation next week, which she'll practice in lab meeting on Friday.

**Comment by ValentineHerr** [comment]
done

**Comment by teixeirak** [comment]
Thanks! @Troger4 , these are ready. I'll send more instructions later.

**Comment by Troger4** [comment]
Thank you!  @teixeirak Where do I access the variables spreadsheet? Is this the same as ForC_variables_mapping.csv?

**Comment by teixeirak** [comment]
It has a lot of overlapping info, but the updated numbers should all be in ForC_variables, in the same spreadsheet as the other data sheets.

**Comment by Troger4** [comment]
Found it, thanks very much for the clarification!
