### ISSUE TITLE
map figure: adjust wording

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#238]
@ValentineHerr , when you get a chance...

The wording on our map figures (e.g., https://github.com/forc-db/ForC/blob/master/figures/World_Map_with_Biomes_and_ForC_simplified_sites_for_ERL_review.png) is somewhat misleading. Could you please change the label "Forest Cover"  to "Dominant Tree Type"?

I also noticed that [this map version](https://github.com/forc-db/ForC/blob/master/figures/World_Map_with_Biogeographic_regions_and_sites.png) has a messed up label on the bar chart.

**Comment by ValentineHerr** [comment]
Done.

I was also thinking that the "No. of records", "No. of plots" etc... was a little confusing as we are not showing a number but a percentage, or just the distribution of records in the different biome. Would that be okay with you if I replaced that by just "records", "plots" and "sites?

**Comment by teixeirak** [comment]
Thanks!

And sure, I think that works to drop "No. of..."

**Comment by ValentineHerr** [comment]
Her you go. I think I can close this.

**Comment by teixeirak** [comment]
Thanks! I just noticed one other little thing-- with the reworded label, we should drop the "other" category from the legend.
