### ISSUE TITLE
Reference Sources? 

### ISSUE THREAD

**Issue by mawilliams99** [forc-db/ForC#243]
What are the possible inputs for source.type and data.location.within.source for references? Currently I've been using 'Table', 'Digitized', and 'Paper.' @ValentineHerr

**Comment by teixeirak** [comment]
@ValentineHerr , just to make sure this is clear, we need to know what your code looks for in the data.location.within.source field.

@mawilliams99 , the source.type options should be in the metadata.

**Comment by ValentineHerr** [comment]
@mawilliams99, I exclude any records for which  `source.notes`  includes "Figure" or "Fig", or "digitized". 

I am realizing now that I am not looking `data.location.within.source`... 
I'll fix that so any records for which  `source.notes` OR `data.location.within.source`  includes "Figure" or "Fig", or "digitized" will be excluded.
 

(I was only looking at  `data.location.within.source` to see if there was "Table S" to know if we should send SI along with main papaer).

**Comment by teixeirak** [comment]
I think we can close this.
