### ISSUE TITLE
Manlay_2002_cnap - comparison against original

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#247]
For EFDB, @mawilliams99  and I have been looking at Manlay_2002_cnap. 

Table 4 has aboveground biomass, and matches what we have in ForC, so this variable is good to go.

`biomass_ag_understory_C`, `organic.layer_C`,  and `biomass_root_C` do not match what's in Table 4. They may have been digitized from figures, or may have been calculated from the table. Note that all are presented in units of C, which appears to be accurate. They may be combinations of variables: for example, I suspect that biomass_root_C is the sum of fine and coarse roots.

For IPCC to use these, we need to enter the original values from Table 4.

**Comment by mawilliams99** [comment]
I changed biomass_ag_understory_C to biomass_ag_understory_OM to match the data from table 4 within the study. organic.layer_C is missing some variables? I was looking at the litter variable to fill that in from table 4. I corrected data for biomass_root_C and got the values by summing fine and coarse roots.

**Comment by teixeirak** [comment]
Thanks, @mawilliams99 ! I think we can close this now.
