### ISSUE TITLE
Mismatches between site-plot combinations in MEASUREMENTS and PLOTS

### ISSUE THREAD

**Issue by bpbond** [forc-db/ForC#25]
First, there are 30 `sites.sitename` values that appear in MEASUREMENTS that don't appear in PLOTS. These are all sites with apostrophes in the name, which sounds like is due to a known bug in MATLAB or the script you're using.

Second, there are 58 (but only 5 unique) plot names in MEASUREMENTS that don't appear in PLOTS.

measurementID | plot.name
-- | --
2654 | Eucalypt open-forest savanna
6488 | birch stand_age55
6489 | birch stand_age55
6032 | EMS Tower (HFR1) _age92
6045 | EMS Tower (HFR1) _age92
1859 | Mature lowland 'wet' perfmafrost-free spruce forest
(lots more)  | Mature lowland 'dry' perfmafrost-free spruce forest
136 | mature 'old growth' forest
(lots more)  | mature 'old growth' forest

(Note I haven't run any trim whitespace or capitalization fixes on these data, so could be something extremely trivial that's causing the match failure.)

In combination, there are 478 site/plot combinations in MEASUREMENTS that don't appear in PLOTS. I'd suggest let's first fix the problems above, and then worry about this. File attached though.
[missing_site_plot_combos.txt](https://github.com/forc-db/ForC/files/1225550/missing_site_plot_combos.txt)

**Comment by teixeirak** [comment]
Thanks, I'll work through these as soon as I get a chance.

**Comment by teixeirak** [comment]
I've confirmed that  the ' character was replaced with " during the process of converting Matlab output back to .csv. It is fixed, albiet with a clunky system ([readme here](https://github.com/forc-db/ForC_private/blob/master/plothistory%20revamp/ForC_plots.xlsx)).

With regards to the missing site names, I believe the last 4 rows should have been solved when the ' character problem was fixed. The first 5 in the list were genuine errors, now fixed. 

With regards to the site-plot combos, in the missing_site_plot_combos.txt file, all plots with name "NI" (no information) got changed to "NA" and counted as a mismatch.

**Comment by bpbond** [comment]
Thanks! I will re-check in a bit. Ah, I see your point about NI ≠ NA.

**Comment by bpbond** [comment]
OK, things looking much better:
```
There are 0 measurements with no corresponding plot record
There are 1 plots with no corresponding measurement record
```

The "1" is this:
```
plotID                  sites.sitename           plot.name
   <int>                           <chr>               <chr>
1   2343 Tapajos NF near km 83 on BR-163 tropical rainforest
```
...and it's true, this `sites.sitename` and `plot.name` combination does not appear in MEASUREMENTS.

**Comment by teixeirak** [comment]
Extraneous plot record removed; thanks for catching it.
