### ISSUE TITLE
Mismatches between MEASUREMENTS and METHODOLOGY

### ISSUE THREAD

**Issue by bpbond** [forc-db/ForC#31]
```
There are 6474 measurement records with no corresponding methodology record
```

This is because three values in MEASUREMENTS$method_id don't appear in METHODOLOGY: `NI`, `NAC`, and `436`.

I assume the first two are a string matching issue--how should this be handled? Do we ignore MEASUREMENT entries with `method_id` equal to NI or NAC?

The last one, `436`, might be a genuine problem?

**Comment by teixeirak** [comment]
NI and NAC are missing value codes, so yes, ignore these. 

436 was a genuine problem. I changed those to NAC, resolving this issue.
