### ISSUE TITLE
finish/load script to plot climate of ForC sites

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#36]
Please load the script used to create this figure: 
![image](https://user-images.githubusercontent.com/6355854/29581216-a05e41fe-8746-11e7-9753-a34b8aa616c4.png)

Modify as follows:
- [ ] add a histogram of Köppen-Geiger climate zones represented in the database (*Koeppen* field in SITES). Use horizontal bars along the x axis to group climate zones into broader categories: A-Tropical; B-Arid; C-Temperate; D-Cold (continental); E- Polar.
- [ ] annotate plots (a) and (b).
- [ ] @bpbond suggests adding global climate space on (a); he may have a suggestion as to one that would work better than Whittaker (which we tried and looked bad).

**Comment by bpbond** [comment]
I did something similar recently, plotting a database over the [CRU climate data](http://www.cru.uea.ac.uk/data) to produce this figure:
![climate_space](https://user-images.githubusercontent.com/1956468/29615741-0f528b24-87dd-11e7-90a3-67596da00dc4.png)
Happy to share code/data if useful.

**Comment by teixeirak** [comment]
I'd like to put that in the background of this figure; it would be great if you could share the code.

**Comment by bpbond** [comment]
Here's the relevant code:
```R
read_csv("outputs/crudata_period.csv.gz") %>%
  print_dims() %>%
  # bin by temp and precip
  mutate(tmp_round = round(tmp / 2, 0) * 2, 
         pre_round = round(pre / 300, 0) * 300) %>%
  group_by(tmp_round, pre_round) %>%
  summarise(area_km2 = sum(area_km2)) ->
  crudata_period

p <- ggplot(crudata_period, aes(tmp_round, pre_round)) + 
  geom_tile(aes(fill = area_km2)) + 
  scale_fill_continuous(low = "lightgrey", high = "black", guide = FALSE) +
  geom_point(data = srdb, aes(mat_hadcrut4, map_hadcrut4, color = Study_midyear), alpha = I(0.5)) + 
  scale_color_continuous(guide = FALSE) +
  xlab(expression(MAT~(degree*C))) + ylab("MAP (mm)")
print(p)
```

**Comment by bpbond** [comment]
[crudata_period.csv.gz](https://github.com/forc-db/ForC/files/1245643/crudata_period.csv.gz)

Here's the data file this code reads, a summary of CRU data for 1990-2014. I can compute another period if you'd prefer.

**Comment by teixeirak** [comment]
Thanks! That time period is great. @ValentineHerr, could you please take a stab at this?

**Comment by ValentineHerr** [comment]
@teixeirak where should we store CRU data? If we use it in the code it should be somewhere.

**Comment by teixeirak** [comment]
Assuming its okay to make it public (@bpbond ?) , lets add a separate "supplementary resources" folder and put it there.

**Comment by ValentineHerr** [comment]
![climate_of_forc_sites](https://user-images.githubusercontent.com/19673377/29636007-082eb49a-881d-11e7-80af-5c54400c78e7.png)

@teixeirak, is this figure working for you ? (I tried to attach it, let me know if that doesn't work).

**Comment by ValentineHerr** [comment]
It needs some twists probably...
@teixeirak, Do you want me to create a new directory to archive the figures ?

**Comment by teixeirak** [comment]
(a) looks wonderful! One small change-- let's do the same as in the original version with black symbols for ForC climate values and white/black outline symbols for those pulled from a database.

for (b), 
- [ ] if feasible, let's separate out by individual climate zone (e.g., separate A into Af, Aw, Am, etc), then put a horizontal bar under each grouping with a label. For example, all A_ climates would be grouped and labeled "tropical"
- [ ] order by climate zone (A- B- C- D- E-) , not ranked by number of sites

Considering the changes to b, it will probably be best to have them stacked instead of side-by-side. There are no size restrictions, so feel free to make them big.

Yes, please create a figures directory.

**Comment by teixeirak** [comment]
let's put both in a folder called supplementary resources/WorldClim data

**Comment by bpbond** [comment]
Re public data, sure, it's just summarized HadCRUT4 data, and those are public.

Figure looks great!

**Comment by ValentineHerr** [comment]
![climate_of_forc_sites](https://user-images.githubusercontent.com/19673377/29639622-67bb187a-8829-11e7-922d-e058c36be097.png)
@teixeirak  is this better/good to go?

**Comment by teixeirak** [comment]
Reopening because I think we still need to load the script

**Comment by ValentineHerr** [comment]
done
