### ISSUE TITLE
write script to make a histogram of number of records by measurement date

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#38]
This will be Fig. 1 in the data paper.

Here's what we want:

Histogram showing years in which data were collected or originally published. For records lacking information on the year in which measurements were made, we substitute year of the data’s original publication. If this is unknown (## records), the record is excluded from this histogram. 

Shade black when we have the year of measurement, grey for year of publication. 

Please include records with start/end date (as opposed to just date)—use end date.

**Comment by ValentineHerr** [comment]
@teixeirak Do you want me to to 5-year bins for the dates or is this good?
![histogram_of_number_of_records_by_measurement_date](https://user-images.githubusercontent.com/19673377/29882628-9d92ffb0-8d7b-11e7-82b5-7893144713f2.png)

**Comment by teixeirak** [comment]
Sorry for the lagged response.

Let's do 5-year bins. 

This figure is a bit deceptive in that the publication year of data loaded from previous databases (e.g., Luyssaert et al. 2007) lags the year of the actual measurement/ original publication. However, I'd rather explain that in the caption than try to fix it in the figure.

**Comment by ValentineHerr** [comment]
Loaded script and figure.

**Comment by teixeirak** [comment]
I'm not sure if this plot is showing what I had in mind.  Typically, C stock measurements will have a date in the "date" field, while C flux measurements will have dates in start_date and end_date. I know you used end_date, but did you also use date? (I suspect not, because the oldest date, 1934, does not register here.) If you did not use date, all  C stock measurements would have been assigned years based on the publication date.

**Comment by ValentineHerr** [comment]
Is it okay If I do something like:

first use date_end
if missing use date
if also missing use citation.year

?

**Comment by teixeirak** [comment]
Yes. At least in theory, if there's a record for end_date, there's not one for date, and vice versa.

**Comment by teixeirak** [comment]
Also, we want to exclude publication dates when those are for a big compilation. Please exclude the following when they are listed in the 

citations.author and citations.year fields, and count those records as unknown date:

: (Anderson et al. 2006, Litton et al. 2007, Luyssaert et al. 2007, Baldocchi 2008, Keith et al. 2009, Liu et al. 2014, Yu et al. 2014).

**Comment by ValentineHerr** [comment]
I don't see Anderson et al. 2006 in the data base.

For Keith et al. 2009, there is 2 papers. I am taking "Re-evaluation of forest biomass carbon stocks and lessons from the world's most carbon-dense forests" over "Multiple measurements constrain estimates   of net carbon exchange by a Eucalyptus forest", OK ?

**Comment by teixeirak** [comment]
This is because we obtained original citations for all studies in Anderson studies. (That Anderson is me in pre-Teixeira life, by the way!)

It looks like the same is the case for the Keith et al. 2009 data. That study does present several new values, so please leave those.

**Comment by ValentineHerr** [comment]
Ok so I leave blank all records with no dates and cited in Litton et al. 2007, Luyssaert et al. 2007, Baldocchi 2008, Liu et al. 2014, Yu et al. 2014

**Comment by ValentineHerr** [comment]
Now histogram looks like that:
![histogram_of_number_of_records_by_measurement_date](https://user-images.githubusercontent.com/19673377/33998070-77f17a70-e0b4-11e7-88f9-4e908fc05d56.png)

Last bin is not 5 year big... Is that ok?

**Comment by teixeirak** [comment]
Ah, that looks better (in terms of completeness of our records). Perhaps you could have the first bin be pre-1960 (or so), and then break out the rest of the record in narrower bins.

**Comment by ValentineHerr** [comment]
Actually 5-year bin is ideal in that case as it comes out even :
![histogram_of_number_of_records_by_measurement_date](https://user-images.githubusercontent.com/19673377/33999295-23bb56a2-e0b8-11e7-95c2-45b72881533a.png)

This is with 3-year bin (but last bin is only 1 year big):
![histogram_of_number_of_records_by_measurement_date](https://user-images.githubusercontent.com/19673377/33999455-846c90f6-e0b8-11e7-83cb-af13f8e5da0d.png)


Do you have a preference? (I'll fix the x-axis labels if you pick 3-year bins)

**Comment by teixeirak** [comment]
This looks great! Call it final.
