### ISSUE TITLE
load script to make map of ForC sites

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#39]
Please load the code to make this figure:
![image](https://user-images.githubusercontent.com/6355854/29629651-9a07b954-8807-11e7-8fce-ae45b4e03d1d.png)

It would also be good to have a simplified version with minimized height that leaves out the biogeographic zones and chart (for a grant proposal).

**Comment by ValentineHerr** [comment]
@teixeirak, Can I load shapefiles of SYNMAP and WWF Ecoregions in supplementary_resources/World Map data ?

**Comment by ValentineHerr** [comment]
@teixeirak, when you say "leave out the biogeographic zones" do you mean remove colors and leave shades of grey for forest cover?
