### ISSUE TITLE
load/modify script to make histogram of dominant vegetation types

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#40]
Please load the code used to make this figure:
![image](https://user-images.githubusercontent.com/6355854/29629808-12322cc0-8808-11e7-9f98-6ae85cbc00e0.png)

Please make the following modifications:

Rearrange some of the categories:
-change grass or shrubs to just grass
-new category: 2TM, which includes 2TD and 2TE.
-woody other/unclassified- for dominant lifeform=woody and dominant veg = 2TREE, NAC, or anything else

Remove”dominant lifeform” label

Change labels as follows: 2TEN- evergreen needleleaf; 2TDB- broadleaf deciduous; 2TEB-broadleaf evergreen; 2TDN- needleleaf deciduous; 2TM- broadleaf- needleleaf mix

**Comment by ValentineHerr** [comment]
I am getting confused with some of the categories.
Here are the unique combinations of dominantveg and dominant.lifeform found in MEASUREMENTS along with my guess for the category in the plot. @teixeirak, can you review?
dominantveg,dominant.lifeform --> my guess
2TEB,woody --> 2TEB
2TDB,woody --> 2TDB
2TEN,woody --> 2TEN
2TB,woody --> 2TDB
2TM,woody --> 2TM
NAC,woody --> woody other/unclassified
2TDN,woody --> 2TDN
NAC,woody+grass -->  woody other/unclassified
2TREE,woody -->  woody other/unclassified
2TE,woody --> 2TM
2TEN,woody+grass --> 2TEN
2TD,woody --> 2TM
2TDB,woody+grass --> 2TDB
2GRAM,grass --> grass
2TN,woody --> 2TDN
2TEB,woody+grass --> 2TEB
2SHRUB,woody+grass --> savanna ??
2SHRUB,woody -->  woody other/unclassified
2BARE,woody -->  woody other/unclassified

**Comment by ValentineHerr** [comment]
@teixeirak, Just to double check:
2SHRUB,woody+grass --> savanna
2SHRUB,woody --> woody other/unclassified
?

**Comment by teixeirak** [comment]
correct.
