### ISSUE TITLE
Allometric equation #15 missing

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#45]
@teixeirak ,
Allometric equation #15 is  missing in ALLOMETRY but referred to in MEASUREMENTS (allometry column).

**Comment by teixeirak** [comment]
Please remove from measurements, put 'NAC' in its place.

**Comment by ValentineHerr** [comment]
There are 22 allometric equations in ALLOMETRY that have no corresponding records in MEASUREMENTS (neither in allometry nor in allometry2)

@teixeirak, should I delete them or keep for future data ?

**Comment by teixeirak** [comment]
Please keep.
