### ISSUE TITLE
Update metadata and statistics in paper following some cleanup of MEASUREMENTS

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#49]
@ValentineHerr, I just reviewed the ranges of variables and had to make some updates to measurements that will affect our statistics. Here's the commit: https://github.com/forc-db/ForC/commit/1f5e1bd20c2ab8233cbc10b39a3a2c6ce245a3b3. Specifically, we will need to update measurements metadata, numbers of records in the variables table (min and max should be okay), and some of the statistics in the paper (only those pertaining to measurements file). Could you please rerun these?

FYI, the ranges for all other fields were fine.

**Comment by ValentineHerr** [comment]
Can you double check you got all the records for u* friction velocity ?
I get 291 records (you entered 289) with min=0 and max=156 (your max was 0.5)

**Comment by ValentineHerr** [comment]
Also, did you mean to enter "high values verified in original publciation by database PI" in MEASUREMENTS _methodID_ ?

**Comment by teixeirak** [comment]
regarding #1, u* should be <1. I deleted (or should have deleted) ~4 records with values above that.

**Comment by teixeirak** [comment]
regarding 2, that comment should be in the notes field. thanks for catching it!

**Comment by ValentineHerr** [comment]
Reagrding 1, u* measurementID 13532 (in  skukuza) is 156, I'll change that to NA.

regarding 2, I'll move comment to _source_notes_ and retrieve the original _methodID_

**Comment by teixeirak** [comment]
Thanks.

Actually, the bad u* value should be replaced with NAC.


On Dec 15, 2017, at 9:58 AM, ValentineHerr <notifications@github.com<mailto:notifications@github.com>> wrote:


Reagrding 1, u* measurementID 13532 (in skukuza) is 156, I'll change that to NA.

regarding 2, I'll move comment to source_notes and retrieve the original methodID

**Comment by ValentineHerr** [comment]
So I'll leave u* and put NAC in cov1_value.
(I thought I would also delete u* in covariate_1 since there is no info about it anymore)

**Comment by ValentineHerr** [comment]
And method_ID seemed to be NAC for those measurements that had the notes in that field.
