### ISSUE TITLE
standardize and polish column names

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#51]
Standardize and polish column names across tables, metadata, scripts and paper.

I believe it can really improve the opinion of future users of the database who could otherwise think that the lack of attention to details in the database is a bad sign about its quality.

Maybe this can be done after submission of paper but before it gets published?

**Comment by bpbond** [comment]
Agreed. A consistent and clear naming scheme is hugely beneficial to users, and absolutely influences their impression of the data themselves, I think.

**Comment by ValentineHerr** [comment]
List of fields to be changed and new names to be used is [here](ForC/metadata/archive/field_names_polishing.txt)

One field name at a time, change in
1. - [ ] all tables

1. - [ ] all metadata tables

1. - [ ] all scripts

1. - [ ] Entity Relashionship Diagram

1. - [ ] in paper (including updated Entity Relashionship Diagram)

**Comment by ValentineHerr** [comment]
I think I went through all the files and standardized the column names. metadata headers might need some work but I am putting that in issue #52
