### ISSUE TITLE
Database cleanup

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#52]
- [x] Standardize variable names

- [x] Standardize field names (see #51 )

- [x] Break out references list

- [ ] Link sites and plots by unique ID numbers rather than full name

- [x] headers in metadata need some work (not column names of tables, just headers of metadata)

**Comment by teixeirak** [comment]
I created a separate issue (#53) for "standardize variable names".

**Comment by teixeirak** [comment]
last item added as new issue: #66
