### ISSUE TITLE
ensure that ORNL DAAC forest NPP data is in ForC

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#63]
The [ORNL DAAC](https://daac.ornl.gov/cgi-bin/dataset_lister.pl?p=13) has NPP estimates for boreal, temperate, and tropical forests.

At least some of these are already in ForC, and the files for tropical forests are [here](https://github.com/forc-db/ForC_private/tree/master/intermediate%20data%20sheets/intermediary%20databases%20%26%20reference%20lists/ORNL%20Trop%20NPP) in our private repo.  According to Maria's records, she has entered the data included in "(Clark et al., 2001, 2013) and
https://daac.ornl.gov/" (see [this doc](https://github.com/forc-db/ForC_private/blob/master/Data%20sources.docx)); however, a spot check revealed that NPP data from Marafunga, Papua New Guinea is not included. Moreover, I do not believe we've ever downloaded temperate and boreal NPP data. It may be that she only loaded the subset in the Clark compilations.

**Comment by teixeirak** [comment]
@nancyfey123, This would be a good task for you to work on. 

First step-- download data from the [ORNL DAAC site](https://daac.ornl.gov/cgi-bin/dataset_lister.pl?p=13). You'll need to create an account, which is very easy.  

Please download both data files and documentation and save them [here (in our private repository)](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/ORNL_DAAC_NPP).

Please download all data sets for temperate, boreal, and tropical forests. Some of the multi-biome data sets look interesting as well, but I'll need to sort through those.

**Comment by beckybanbury** [comment]
@teixeirak, just so you're updated, I'm working on adding some of these data today.

**Comment by beckybanbury** [comment]
@teixeirak , I have now checked all the data in these files - most was already added but I have completed adding the data that wasn't already present. Let me know if you'd like me to have a look at the multi-biome sets, if you get a chance to have a look over them.

**Comment by teixeirak** [comment]
@beckybanbury, could you please check the user guides of the multi-biome compilations to see if they have any data that's unique/ of value to ForC?

**Comment by beckybanbury** [comment]
@teixeirak , I've been working on this today and have been able to add some new data; quite a lot was already entered or in the wrong format for us though!

I have one dataset left, which I wonder if you'd be able to take a look at? It's the ODS_NPP file, which is saved [here](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/ORNL_DAAC_NPP). Obviously, there is a lot of data there that needs to be excluded, but it looks like there may be some data that we haven't got. I'm a little wary of the methods used however. First, the data guide states that where BNPP wasn't measured, it was assumed to be equal to ANPP when calculating NPP, which seems like a pretty big assumption! Perhaps we would want to exclude this data? Second, the document gives a range of ANPP and BNPP values, so I don't know which we would want to take if we do use them. It would be great if you could take a look and let me know what you think.

**Comment by beckybanbury** [comment]
@teixeirak, having looked more deeply at these data, it looks like most of the data is not reliable or useable. I've found a couple of references that look like they might have useable data, so am working through them. I've also removed some data that I previously added, because, having checked back, I don't think that it's sufficient quality or reliability.

**Comment by teixeirak** [comment]
Thank you!
