### ISSUE TITLE
ensure that tropical ANPP data from Taylor et al. 2017 is included

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#64]
[Taylor et al. 2017](http://onlinelibrary.wiley.com/doi/10.1111/ele.12765/full) compiled tropical ANPP estimates, and data are published [here](https://data.nceas.ucsb.edu/#view/doi:10.5063/F19021QT). This effort was independent of ours. There's probably a fair amount of overlap, but it looks like they have some records we don't.

**Comment by teixeirak** [comment]
also, this publication (probably everything in here is in Taylor):

Cleveland, C. C., A. R. Townsend, P. Taylor, S. Alvarez-Clare, M. M. Bustamante, G. Chuyong, S. Z. Dobrowski, P. Grierson, K. E. Harms, B. Z. Houlton, A. Marklein, W. Parton, S. Porder, S. C. Reed, C. A. Sierra, W. L. Silver, E. V. Tanner, and W. R. Wieder. 2011. Relationships among net primary productivity, nutrients and climate in tropical rain forest: a pan-tropical analysis. Ecology Letters 14:939-947.

**Comment by teixeirak** [comment]
@beckybanbury, this is one of the data sources I mentioned yesterday. I just wrote Cory Cleveland about these data; awaiting response.

**Comment by beckybanbury** [comment]
@teixeirak, great, let me know when you hear back! Do we have the FLUXNET data saved anywhere; so far I've just found the site list? If not, I will download.

**Comment by teixeirak** [comment]
From Cory Cleveland:

The data are public; we're welcome to use them. There's an updated database with much more data in the works, and he's checking with collaborators as to whether we can use that. 

[This link](https://knb.ecoinformatics.org/view/doi:10.5063/F19021QT) should work to the old database. There are four excel files (litterfall [“canopy” column]; stem growth [“woody” column; decomposition [“k” column]; and ANPP [“ANPP” column] in the respective files). The metadata file at this link is still broken but the labels should be self-explanatory (MAP, MAT, Lat, Lon, Reference, Country, etc.). The ID # is only relevant to our specific analysis. He's happy to field questions.

**Comment by beckybanbury** [comment]
@teixeirak, there is some data in this set from a dissertation that has not been published in a journal as far as I can tell; do we include this or not?

**Comment by teixeirak** [comment]
Yes, data that are published in intermediary sources are counted as meeting the “published criteria, even if personal communication.

**Comment by beckybanbury** [comment]
Great! What should I enter in the citation.ID column for these sources?

**Comment by teixeirak** [comment]
If there’s a full citation available, create an entry in citations. If personal comm, put the published source (here, Taylor) and list personal comm source in notes.

**Comment by beckybanbury** [comment]
@teixeirak, I have now completed entering the litterfall, stem growth and total ANPP data from this database.

**Comment by teixeirak** [comment]
Wonderful, thank you!

**Comment by teixeirak** [comment]
Wonderful, thank you!
