### ISSUE TITLE
write script to create analysis-ready table ("ForC-simplified")

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#65]
As a first step for most data analyses and to facilitate use of the database, I'd like to create a script that does some preliminary data manipulation and outputs a single spreadsheet containing the fields that will most commonly be used in analysis.

Script should do the following:
- [ ] convert all measurements to units of C (use IPCC default C=0.47*biomass).
- [ ] resolve duplicate records (following guidelines of issue #68)
- [ ] potentially, combine variables to calculate others according to a set of equations governing relationships among variables (issue #67).

Fields to be contained in this table will be defined through issue #69.

**Comment by teixeirak** [comment]
I have created a folder for and described this spreadsheet [here](https://github.com/forc-db/ForC/blob/master/ForC_simplified/README.md).

**Comment by ValentineHerr** [comment]
@teixeirak and @nancyfey123,
I uploaded the [ForC_simplified](https://github.com/forc-db/ForC/blob/master/ForC_simplified/ForC_simplified.csv) table with the [R code](https://github.com/forc-db/ForC/blob/master/scripts/Database_manipulation/Create_ForC_simplified.R) that generates it.
**IMPORTANT NOTE**: The current version does not have the duplicates issue resolved. So be prepared to re-run whatever analysis you do on that later.

**Comment by teixeirak** [comment]
Thanks!

**Comment by teixeirak** [comment]
Looking wonderful, but did you forget to push the final version? I see only fields from SITES & PLOTS tables.

**Comment by nancyfey123** [comment]
I pushed the final version before I sent a pull request! Is there an additional step I may have forgotten? I have yet to change it in the other tables as you instructed last night since I’m working on the stand ages in the measurements table

**Comment by teixeirak** [comment]
@nancyfey123, my message was in response to @ValentineHerr. You're fine!

**Comment by teixeirak** [comment]
@ValentineHerr, please note two additional simplifications to include:
NEE_cum_C, GPP_cum_C, and R_eco_cum_C ignored.
Secondary variables ignored. 

Also, please note metadata change in issue #81

**Comment by teixeirak** [comment]
Yes, that's correct. Thank you!

One other minor thing for now: Please rearrange column order to put the fields from measurements first (so first field is measurement.id.

**Comment by ValentineHerr** [comment]
ok done!

**Comment by teixeirak** [comment]
Thank you!!

**Comment by teixeirak** [comment]
@ValentineHerr, Please modiffy the code such that true (1) values in *management.other.ID* do not get counted towards true values in *managed* field of ForC-simplified.

**Comment by ValentineHerr** [comment]
@teixeirak, what do you mean by "true (1) values" ?

**Comment by teixeirak** [comment]
value = 1, following convention that 1=true, 0=false.

**Comment by ValentineHerr** [comment]
Ok I fixed that in this comit: 6e6f337
That affected 8 records. Let me know if that doesn't sound right.

**Comment by teixeirak** [comment]
Sounds right, thanks.

**Comment by teixeirak** [comment]
@ValentineHerr, I added a field to MEASUREMENTS that flags suspicious records that shouldn't be used in analyses until they are checked. Could you please modify your code to exclude any records with flag.suspicious=1? There are currently only two records in this category.

**Comment by ValentineHerr** [comment]
@teixeirak, at what stage should I deal with this ?
1- When creating ForC_simplified? (removing all flag.suspicious=1)
2- When doing analysis and average per Biomes ?

Note, I remove managed and disturbed sites at stage 2 (the 2 fields are created in stage 1).

**Comment by ValentineHerr** [comment]
We remove suspicious records when creating ForC_simplified
