### ISSUE TITLE
Define rules for selecting among duplicate records

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#68]
@teixeirak needs to define the best default procedure for selecting among duplicate records. 

This is necessary to complete issue #65.

**Comment by teixeirak** [comment]
Here are the rules I'd like to apply:
For each variable, reconcile duplicate records (indicated in dup.code and dup.num fields of MEASUREMENTS table). 
- Replicate measurements (‘R’ code) should be averaged. 
- For duplicate records reported by different studies (D, DC, or P codes), priority should be given to the most recently published estimate (i.e., highest number in dup.num field). 
- For duplicates that differ only in methodology (M code), code should select records with the highest value. We need to review and adjust the  dup.code as necessary to ensure that the higher number is assigned to the record employing a more comprehensive approach (e.g., inclusion of understory, lianas, or bamboo as opposed to just trees) or using a more rigorous or standard methodology. Then

**Comment by ValentineHerr** [comment]
@teixeirak ,
I am working with dup.code "R", what should I do with stats associated to records ?
For example, at  _sites.sitename_ POP-EUROFACE, _plot.name_ ambient POP-EUROFACE euramericana, _variable.name_ biomass_root_OM, one record has NI for _stat.name_ and _stat_, while the second has values (SE and 0.32, respectively).

**Comment by ValentineHerr** [comment]
@teixeirak ,
Same question with _n_... should I do a weighted average ?

**Comment by ValentineHerr** [comment]
@teixeirak ,
Some records with code "R" are measurements made at different depth... are they really duplicates ?
See, for example, _sites.sitename_ Saldarriaga chronosequence II, _plot.name_ Saldarriaga chronosequence II, _stand.age_ 11, _variable.name_ biomass_root_OM.

**Comment by teixeirak** [comment]
I think we may have some confusion... I'm not talking about merging records, just selecting the preferred one.

**Comment by ValentineHerr** [comment]
I thought the "R" codes should be averaged ?

**Comment by teixeirak** [comment]
Right. We won't actually modify the measurements table, just draw relevant info from it. In general, we don't need to bother with reconciling all the fields; let's fill it in with an "NA.R" code.  I'll give specific answers on all of your questions below.

**Comment by teixeirak** [comment]
stats associated to records ?
For example, see measurement.ID 11191 and 11192. One record has NI for stat.name and stat, while the second has values (SE and 0.32, respectively).

*use NA.R*

covaritates ?
For example, see measurement.ID 11630 and 11631. One record has NAC for covaraite_1 and coV_1.value, while the second has values ( min.diameter_root and 5, respectively).

*In this specific instance its clear that min.diameter was just left off of one record (same study, all other biomass_root_coarse_OM records have the same min.diameter), so I corrected. If they're true replicates, all covariates should be the same, so if one record has a missing value code, use the covariate from the record that has a value. If there a different values for the same covariate, its not a true replicate (R code)-- should be M instead.* 

n ? ... should I do a weighted average ?
For example, see measurement.ID 11668 and 11669.

*Yes, good idea.*

depth ?
Some records with code "R" are measurements made at different depth... are they really duplicates ?
For example, see measurement.ID 12681, 12684, 12685, 12686, 12687.

*No, these are not replicates. These should have the "M" code. I fixed the particular instance of this study, and would appreciate if you could fix any others you encounter.*

notes, source.notes ? (thinking of ignoring)
For example, see measurement.ID 12681, 12684, 12685, 12686, 12687. (notes)
For example, see measurement.ID 7111-7116. (source.notes)

*use NA.R.*

_ min.dbh_ ?
For example, see measurement.ID 4135 and 4136.

*Again, these are not replicates. These should have the "M" code. I fixed the particular instance of this study, and would appreciate if you could fix any others you encounter.*

loaded.by ? (thinking of ignoring)
For example, see measurement.ID 11499 and 11500.

*use NA.R.*

method.ID ? --> should they have different dup.code ?
For example, see measurement.ID 14038 and 14039.

*Again, these are not replicates. These should have the "M" code. I fixed the particular instance of this study, and would appreciate if you could fix any others you encounter.*
