### ISSUE TITLE
calculate dates of forest regeneration in plot history

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#7]
@mmw590, I added entries in the plot history for all the previously missing sites/plots. There are quite a few that have age data in the measurements file. If you have code to calculate their regeneration dates based on age and date of measurement, it would be great to add those dates to the measurements file. See notes therein.

**Comment by mmw590** [comment]
I have Excel code to calculate stand.age from dates in 'datavalidationonlyNOENTRY' tab in 2ForC_data_sites_plothistory.xlsx, if that's useful. 
![image](https://cloud.githubusercontent.com/assets/10426014/23757565/34c11f3e-04b5-11e7-9133-58911f19ccf8.png)

**Comment by teixeirak** [comment]
Done

**Comment by teixeirak** [comment]
I did this but somehow lost the changes.

**Comment by teixeirak** [comment]
Done.
