### ISSUE TITLE
Check some records

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#73]
As I am working on some of the issues I find problems in the data that need @teixeirak's attention. I'll post them here as I find them.

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ **from** 4078 **to** 4087: double check notes and min.dbh as they don't seem to match. Once that is solved, fix dup.code accordingly.

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ 7988 and 7990: double check _stand.age_ and/or _date_ because _stand.age_ is the same while the measurements were made 3 years apart.

**Comment by ValentineHerr** [comment]
- [ ] should we replace NA by NAC in _date_, _start.date_ and _end.date_ ? (and maybe other fields but for now these are the ones that would help me with some of the coding, but not a big deal, I have a way around)

**Comment by teixeirak** [comment]
Regarding missing values codes in dates... NAC and NA have different meanings. date should generally be "NA" for fluxes (with start & end date) and start.date and end.date should be NA for stocks, although a quick review shows that that's not universally the case.  NAC should be applied when dates were not acquired. I replaced some NACs by NA, but a quick review didn't show any NAs that should be NAC.

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ 7111 and 7116: Do you know why everything is the same (including _method.ID_) but _mean_ are different ? one of them is quite low compared to the others,  and _source.notes_ is missing for it.

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ 1684 and 1685: Do you agree that they should not be duplicates ?

**Comment by teixeirak** [comment]
measurement.ID 7111 and 7116- these appear to be true replicates.

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ 3274 and 3279: Do you agree that they should not be duplicates ? actually different plot.name, right ?
-[ ] _measurement.ID_ 3275 and 3280: same
-[ ] _measurement.ID_ 3276 and 3281: same
-[ ] _measurement.ID_ 3277 and 3282: same
-[ ] _measurement.ID_ 3278 and 3283: same

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ 7988 and 7990: check _date_ (_stand.age_ is same but _date_ is different)

**Comment by ValentineHerr** [comment]
- [ ] is _measurement.ID_ 3627 really a duplicate ? Right now it is pooled with 3581 and 3597 but dates are differents
- [ ]  is _measurement.ID_ 3629 really a duplicate ? Right now it is pooled with 3585 and 3599 but dates are differents

**Comment by ValentineHerr** [comment]
- [ ] _measurement.ID_ from 3622 to 3630: check _date_ and _stand.age_ (_stand.age_ changes while _date_ doesn't)

**Comment by ValentineHerr** [comment]
- [ ] is _measurement.ID_ 8164 really a duplicate ? Right now it is pooled with 8136 and 8149 but dates are different
- [ ] is _measurement.ID_ 8162 really a duplicate ? Right now it is pooled with 8126, 8147 and 8150 but dates are different
- [ ] is _measurement.ID_ 8163 really a duplicate ? Right now it is pooled with 8131 and 8148 but dates are different

**Comment by ValentineHerr** [comment]
@teixeirak I am finding too many issues (140) to keep reporting them like that.
Not sure what is the best way to tackle that.
Below is a list of the 140 instances to look for. They can be anything from _date_ and _stand.age_ discrepancies, to missing "DC" in _dup.code_ for either the _OM or the _C record of the same variable.

The list is made of concatenated   _sites.sitename_, _plot.name_ ,  _variable.name_ (ignoring _C or _OM), _date_, _stand.age_, _start.date_. I find it when looking at all records that have the same value for all  these fields  AND a _dup.code_ other than "0" BUT that end up being the only one observation (there should be at least 2 if they have a _dup.code_).

Let me know how you think I should move forward.

- [ ] Collelongo.Managed.GPP.NA.106.1996.489071
- [ ] Collelongo.Managed.R_eco.NA.106.1996.489071
- [ ] Le Bray.Managed 1970 pine plantation.GPP.NA.28.1996.530055
- [ ] Le Bray.Managed 1970 pine plantation.NEE.NA.28.1996.530055
- [ ] Le Bray.Managed 1970 pine plantation.R_eco.NA.28.1996.530055
- [ ] Bayreuth/Weiden Brunnen.Managed.GPP.NA.47.1997.328767
- [ ] Bayreuth/Weiden Brunnen.Managed.NEE.NA.47.1997.328767
- [ ] Bayreuth/Weiden Brunnen.Managed.R_eco.NA.47.1997.328767
- [ ] Hyytiala Scots Pine Chronosequence 75.Stand development of an unmanaged plantation.GPP.2001.76.2001.186301
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.BNPP_root_fine.NA.85.2003
- [ ] San Carlos de Rio Negro Species-rich Tierra Firme (Oxisols).UM Mature terra firma.ANPP_litterfall_1.NI.999.NI
- [ ] San Carlos de Rio Negro Species-rich Tierra Firme (Oxisols).UM Mature terra firma.ANPP_woody_stem.NI.999.NI
- [ ] Yapo (Plateau).Mature .biomass_ag.NI.999.NI
- [ ] San Carlos de Rio Negro Species-rich Tierra Firme (Oxisols).UM Mature terra firma.BNPP_root_fine.NI.999.NI
- [ ] ORNL-FACE.ambient ORNL-FACE.NPP_1.1998.10.NA
- [ ] ORNL-FACE.elevated CO2 ORNL-FACE.NPP_1.1998.10.NA
- [ ] ORNL-FACE.ambient ORNL-FACE.NPP_1.1998.665753.10.NA
- [ ] ORNL-FACE.elevated CO2 ORNL-FACE.NPP_1.1998.665753.10.NA
- [ ] Collelongo.Managed.NEE.1993.103.NA
- [ ] Collelongo.Managed.NEE.1993.104.NA
- [ ] ORNL-FACE.ambient ORNL-FACE.NPP_1.1999.665753.11.NA
- [ ] ORNL-FACE.elevated CO2 ORNL-FACE.NPP_1.1999.665753.11.NA
- [ ] Thompson NSA (NOBS).UM.biomass_root.1994.114.NA
- [ ] Thompson NSA (NOBS).UM.biomass_root_coarse.1994.114.NA
- [ ] Thompson NSA (NOBS).UM.biomass_root_fine.1994.114.NA
- [ ] Thompson NSA (NOBS).UM.GPP.1994.114.NA
- [ ] Thompson NSA (NOBS).UM.biomass_root.1994.665753.114.NA
- [ ] Thompson NSA (NOBS).UM.biomass_root_coarse.1994.665753.114.NA
- [ ] Thompson NSA (NOBS).UM.biomass_root_fine.1994.665753.114.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_ag.1994.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_root.1994.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_root_coarse.1994.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_root_fine.1994.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.GPP.1994.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_ag.1994.580822.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_root.1994.665753.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_root_coarse.1994.665753.115.NA
- [ ] Prince Albert SSA (SOBS).natural regeneration after 1879 wildfire.biomass_root_fine.1994.665753.115.NA
- [ ] ORNL-FACE.ambient ORNL-FACE.NPP_1.2000.666667.12.NA
- [ ] ORNL-FACE.elevated CO2 ORNL-FACE.NPP_1.2000.666667.12.NA
- [ ] Aberfeldy/Griffins.plantation forest.GPP.1997.17.NA
- [ ] Aberfeldy/Griffins.plantation forest.NEE.1997.17.NA
- [ ] Aberfeldy/Griffins.plantation forest.R_eco.1997.17.NA
- [ ] Aberfeldy/Griffins.plantation forest.GPP.1998.18.NA
- [ ] Aberfeldy/Griffins.plantation forest.NEE.1998.18.NA
- [ ] Aberfeldy/Griffins.plantation forest.R_eco.1998.18.NA
- [ ] Thompson NSA (NYJP).NI.biomass_ag.1994.25.NA
- [ ] Thompson NSA (NYJP).NI.biomass_ag.1994.580822.25.NA
- [ ] Harwood CarboAge Chronosequence.Managed 30-y second rotation.GPP.2001.30.NA
- [ ] Harwood CarboAge Chronosequence.Managed 30-y second rotation.NEE.2001.30.NA
- [ ] Harwood CarboAge Chronosequence.Managed 30-y second rotation.R_eco.2001.30.NA
- [ ] Hesse.Managed.R_soil_het.1997.31.NA
- [ ] Le Bray.Managed 1970 pine plantation.biomass_ag.2003.34.NA
- [ ] Le Bray.Managed 1970 pine plantation.biomass_ag_foliage.2003.34.NA
- [ ] Le Bray.Managed 1970 pine plantation.biomass_ag_woody.2003.34.NA
- [ ] Le Bray.Managed 1970 pine plantation.GPP.2003.34.NA
- [ ] Le Bray.Managed 1970 pine plantation.NEE.2003.34.NA
- [ ] Le Bray.Managed 1970 pine plantation.R_eco.2003.34.NA
- [ ] Takayama.secondary deciduous forest.GPP.1994.36.NA
- [ ] Takayama.secondary deciduous forest.R_eco.1994.36.NA
- [ ] Takayama.secondary deciduous forest.GPP.1995.37.NA
- [ ] Takayama.secondary deciduous forest.R_eco.1995.37.NA
- [ ] Takayama.secondary deciduous forest.GPP.1996.38.NA
- [ ] Takayama.secondary deciduous forest.R_eco.1996.38.NA
- [ ] Takayama.secondary deciduous forest.GPP.1997.39.NA
- [ ] Takayama.secondary deciduous forest.R_eco.1997.39.NA
- [ ] Takayama.secondary deciduous forest.GPP.1998.40.NA
- [ ] Takayama.secondary deciduous forest.R_eco.1998.40.NA
- [ ] Harwood CarboAge Chronosequence.Managed clear-cut in 1960.40-y first rotation.GPP.2001.41.NA
- [ ] Harwood CarboAge Chronosequence.Managed clear-cut in 1960.40-y first rotation.NEE.2001.41.NA
- [ ] Harwood CarboAge Chronosequence.Managed clear-cut in 1960.40-y first rotation.R_eco.2001.41.NA
- [ ] Thompson NSA (NOAS).NI.biomass_ag.1994.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_root.1994.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_root_coarse.1994.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_root_fine.1994.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_ag.1994.580822.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_root.1994.665753.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_root_coarse.1994.665753.53.NA
- [ ] Thompson NSA (NOAS).NI.biomass_root_fine.1994.665753.53.NA
- [ ] Walker Branch.UM, agricultural abandonment in 1940.GPP.1999.59.NA
- [ ] Walker Branch.UM, agricultural abandonment in 1940.NEP.1999.59.NA
- [ ] Walker Branch.UM, agricultural abandonment in 1940.R_eco.1999.59.NA
- [ ] Puechabon.Managed.evergreen oak coppice woodland.NEE.2003.60.NA
- [ ] Thompson NSA (NOJP).NI.biomass_ag.1994.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_root.1994.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_root_coarse.1994.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_root_fine.1994.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_ag.1994.580822.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_root.1994.665753.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_root_coarse.1994.665753.63.NA
- [ ] Thompson NSA (NOJP).NI.biomass_root_fine.1994.665753.63.NA
- [ ] WLEF tower in Park Falls Ranger District.Managed for logging.NEE.2000.64.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_ag.1994.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_root.1994.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_root_coarse.1994.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_root_fine.1994.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.GPP.1994.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_ag.1994.580822.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_root.1994.665753.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_root_coarse.1994.665753.65.NA
- [ ] Prince Albert SSA (SOJP).natural regeneration after 1929 wildfire.biomass_root_fine.1994.665753.65.NA
- [ ] Lake States Warba soil aspen chronosequence 2a.Lake States Warba soil aspen chronosequence 2a.total.ecosystem.1973.66.NA
- [ ] Lake States Warba soil aspen chronosequence 2a.Lake States Warba soil aspen chronosequence 2a.total.ecosystem.1976.66.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_ag.1994.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_root.1994.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_root_coarse.1994.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_root_fine.1994.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.BNPP_root_fine.1994.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_ag.1994.580822.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_root.1994.665753.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_root_coarse.1994.665753.75.NA
- [ ] Prince Albert SSA (SOAS).natural regeneration after 1919 fire.biomass_root_fine.1994.665753.75.NA
- [ ] Hyytiala Scots Pine Chronosequence 75.Stand development of an unmanaged plantation.GPP.2001.76.NA
- [ ] Solling project B3.Forest recovery following clear-cut.80y.biomass_ag.1969.80.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.GPP.1996.84.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.NEE.1996.84.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.R_eco.1996.84.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.GPP.1997.85.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.NEE.1997.85.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.R_eco.1997.85.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.GPP.1998.86.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.NEE.1998.86.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.R_eco.1998.86.NA
- [ ] Soroe.Managed.NEE.2002.86.NA
- [ ] Soroe.Managed.R_eco.2003.86.NA
- [ ] Soroe.Managed.R_eco.2003.87.NA
- [ ] Harvard Forest - Little Prospect Hill.EMS Tower (HFR1) .GPP.2000.89.NA
- [ ] Harvard Forest - Little Prospect Hill.EMS Tower (HFR1) .R_eco.2000.89.NA
- [ ] Brasschaat.Managed.NEE.1997.92.NA
- [ ] Harvard Forest - Little Prospect Hill.EMS Tower (HFR1).NEE.2003.92.NA
- [ ] Harvard Forest - Little Prospect Hill.EMS Tower (HFR1) .NEE.2003.92.NA
- [ ] Brasschaat.Managed.NEE.1998.93.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.GPP.1996.96.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.R_eco.1996.96.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.GPP.1997.97.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.R_eco.1997.97.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.GPP.1998.98.NA
- [ ] Camp Borden.natural regeneration on abandoned farmland.R_eco.1998.98.NA
- [ ] YAP-01b_Yapo IBP.african tropical forest.biomass_ag.1974.999.NA
- [ ] Wytham Woods.ancient semi-natural woodland.R_soil.2008.999.NA

**Comment by teixeirak** [comment]
1. It is likely that these are cases where fluxes have been calculated over different time periods and therefore are not true duplicates (more like semi-duplicates). For example, record 1347 partially duplicates both 1329 and 1330. We'll generally want to drop these instances where a single record partially duplicates others that are part of a longer sequence (e.g., records 1329-1331) rather than breaking up the sequence. Of course, we still need to assign these records to those that they closely duplicate. Please round dates to the closest year when necessary. For fluxes, assume that e.g., 1997 means Jan 1 1997 - Dec 31 1997.

**Comment by teixeirak** [comment]
2. I don't understand what you mean about a problem with format.  Are you referring to the fact that some records are more precise (include fractional year)? Or perhaps that some fluxes are given a single date rather than start & end date? Please clarify.

**Comment by teixeirak** [comment]
3. These records should all be resolved.

**Comment by teixeirak** [comment]
4. This is resolved.

**Comment by ValentineHerr** [comment]
2. Yes I am referring to the fact that some dates are more precise (including fractional year).
Is it ok if I just ignore the fraction and take only the integer part of the year to group the duplicates together ?

**Comment by teixeirak** [comment]
Yes, please do that. Note that eddy flux records indicating just a year will typically be Jan1-Dec31 of that year, and dates should typically be more precise than indicated by the date.loc code. 

For assigning priority to such records, we'll generally want to drop instances where measurement records partially duplicates others that are part of a longer sequence rather than breaking up the sequence. For instance, if we have a site with flux records for years 2000, 2001, and 2002, and another record May 2001-April 2002, we'd want to drop the latter.

**Comment by teixeirak** [comment]
5. I don't think  Brasschaat.Managed.NEE.1997.92.NA is a duplicate.

**Comment by teixeirak** [comment]
An update on dup.nums, now in metadata: "A dup.num=0 indicates that no rank was assigned because duplicates were average across multiple years or that records lack the information required to assign a rank."

**Comment by teixeirak** [comment]
I believe I have dealt with everything here.

**Comment by ValentineHerr** [comment]
Re-opening this issue for random questions and issues related to some records

**Comment by ValentineHerr** [comment]
- [ ] there are 7 records with either start.date OR end.date. Is that ok?
fortunately none of them are duplicated (at least they don't seem to be) but I just want to make sure it is not an error in the data.

**Comment by teixeirak** [comment]
Are these stocks or fluxes? Can you give me the IDs so I can check?

**Comment by ValentineHerr** [comment]
1682  1683  1684  1685 15303 15304 15305

**Comment by teixeirak** [comment]
Okay, the first four are records where date was only expressed relative to a hurricane, which I looked up and used to constrain dates. The last 3 had a note in the comments, and I just edited the file to reflect that.

**Comment by ValentineHerr** [comment]
- [ ] There are 65 records with both date and start.date. All But 1 record (ID 16977) has the end.date  within a year.
I'll always look at date as a priority over range of date if that is ok.

BUT what should I do for that one record (16977) ?

**Comment by ValentineHerr** [comment]
I don't see the changes for those records pre and post huricane.

**Comment by teixeirak** [comment]
I just fixed the date on 16977.
I didn't change the hurricane records.

**Comment by ValentineHerr** [comment]
- [ ] measurements ID 224, 225 and 226 have same _stand.age_ but different _date_ (including one missing)

**Comment by teixeirak** [comment]
This is fixed, but in the process I accidentally created a conflicted copy. Could you please resolve that with your version. The difference is in Ma_2012 records-- stand.age & date.

**Comment by ValentineHerr** [comment]
Problem of _stad.age_ and _date_ discrepancy

- [ ] 5296 and 5297
- [ ] 5292, 5293
- [ ] 5288, 5289
- [ ] 5290, 5291
- [ ] 5294, 5295
- [ ] 5298, 5299
- [ ] 3510, 3511, 3512

**Comment by ValentineHerr** [comment]
end date comes before start date for these records:

- [ ] 4002
- [ ] 4005
- [ ] 4011

**Comment by ValentineHerr** [comment]
@teixeirak ,
in MEASUREMENTS table, the plot name for "Solling project B1" is "Forest recovery following clear-cut.**80y**" while it is "Forest recovery following clear-cut.**122y**" in the PLOTS table.
Looks like there might have been a mismatch at some point.

**Comment by teixeirak** [comment]
"Forest recovery following clear-cut.122y" is the correct plot name. Please change plot name on records 13581-13586 to this.

**Comment by ValentineHerr** [comment]
ok thanks, done.

**Comment by ValentineHerr** [comment]
@teixeirak 
The following recorsd in PLOTS table seem to be exact duplicates. Can I delete them? If yes, can I overwrite the _plot.ID_ of Zuogong ?

ID|plot.ID|sites.sitename|plot.name
--|--|--|--
1|2725|Zhongdian Picea| Abies|Picea| Abies
2|2726|Zhongdian Quercus|Quercus
3|2727|Zhongtie|Juniperus przewalskii
4|2728|Zhuwagen Picea| Abies|Picea| Abies
5|2729|Zhuwagen Quercus|Quercus
6|2730|Zotino|Pinus sylvestris

**Comment by teixeirak** [comment]
That's an error originating from me (oops!). Yes, please delete the duplicate records. I'm confused about overwriting the plot.ID of Zuogong; it will still follow sequentially once duplicates are deleted.

**Comment by ValentineHerr** [comment]
Indeed! I didn't even check that... ok, done!

**Comment by ValentineHerr** [comment]
- [ ] The note in _measurement.ID_ 5947 says "for trees dbh >5cm" but the min.dbh is "NAC". Note that the one duplicate of that record (ID 16933) says "for all plants".

**Comment by ValentineHerr** [comment]
@teixeirak ,

There is 69 records that have both _date_ and _start.date_ and _end.date_. Is it ok if I ignore _date_ in my code? Should we delete date in the master so that it is not in the way of future work ?

**Comment by teixeirak** [comment]
Yes, okay to ignore. I don't see a need to delete. They should be equivalent information.
