### ISSUE TITLE
add DeAngelis 1981 data

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#77]
DeAngelis 1981 has a lot of data that have not yet been included in ForC, including productivity data. 

Some of it is available in digital format, [here](https://github.com/forc-db/ForC_private/tree/master/intermediate%20data%20sheets/intermediary%20databases%20%26%20reference%20lists/DeAngelis%20NPP_IBP_198). At least a lot of this was included in Luyssaert and is therefore in ForC; however, Luyssaert seems to have included only summary data, not some of the component data that is available and may be of interest (e.g., deadwood, ANPP_repro, ANPP_folivory). Component data is given in the study [pdf](https://github.com/forc-db/References/blob/master/DeAngelis_1981_pofe.pdf).

**Comment by teixeirak** [comment]
@nancyfey123, this would be another good issue for you to work on. 

The first step will be digitizing the data of interest in this  [pdf](https://github.com/forc-db/References/blob/master/DeAngelis_1981_pofe.pdf). Each site has a subset of data (above the horizontal line) that has already been digitized and is in our repository [here](https://github.com/forc-db/ForC_private/tree/master/intermediate%20data%20sheets/intermediary%20databases%20%26%20reference%20lists/DeAngelis%20NPP_IBP_198). However, the data below the line has not been digitized (at least to my knowledge). 

For now, you can just make a matrix of sites and variables (use list at beginning of pdf). Please include definitions for each accronymn. Once this is done, I'll provide guidance on linking variables to the ForC variables, linking with ForC sites, and entering the data.

**Comment by nancyfey123** [comment]
Hi Krista.

I’m out of the hospital as of this weekend and will begin working in these issues.

--
Nancy Fey
Environmental Science Student
George Mason University
P (609) 670-7687
E nfey@masonlive.gmu.edu
--
________________________________

**Comment by teixeirak** [comment]
@nancyfey123, I loaded the data you digitized [here](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/DeAngelis_1981_pofe). Next step is for me to map ForC variables to these variables.

**Comment by teixeirak** [comment]
@nancyfey123, here are the first steps to processing these data. I'll add more soon. 

1.	Make sure you have  the latest ForC_measurements file
2.	Highlight the top row (field names). Then on the data tab, hit filter. Go to the citation.ID field and select only DeAngelis_1981_pofe. This will show only the data from DeAngelis_1981_pofe that is already in ForC.
3.	Go through your list of sites from DeAngelis and indicate whether they are present in ForC. Its probably easiest to do this if you move through the list of sites in ForC measurements alphabetically, marking those present. 
a.	Site names will not match exactly, but you should be able to identify them.
b.	Note that some sites have similar names, differing only in age or a code.
c.	If there are any about which you are unsure, make a note and move on until I get a chance to look at it.
d.	We will need to add these sites to ForC, and that's something I'll need to help with. Please send me the list once you have it.

**Comment by teixeirak** [comment]
4. Create a new .csv file with the same headings as ForC_measurements but no records.
5.	Moving through the sites that are already in ForC in the order that they appear, compare the list of variables already in ForC to the set available, and identify ForC variables (i.e., those we have defined in ForC VARIABLES table) that are reported but not yet in the database. Mapping of DeAngelis variables to ForC variables is given [here](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/DeAngelis_1981_pofe/DeAngelis_1981_pofe_definitions%26abbreviations.csv). For each of these variables, copy one of the rows in ForC_measurements for an existing record from DeAngelis_1981_pofe for the site. Then modify as follows:
a. delete *measurement.ID* (leave blank). 
b. change *variable.name* to the variable you're entering.
c. verify that *date* matches your records. If not, note it and report to me
d. for *mean*, enter the reported value after multiplying by the conversion factor given [here](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/DeAngelis_1981_pofe/DeAngelis_1981_pofe_definitions%26abbreviations.csv). DeAngelis reports values in g/m2, so the conversion to Mg/ha is dividing by 100.
e. for *notes*, list the original variable name in DeAngelis (may be more than one; e.g., OL+UL).
f. fields *method.ID* through *conflicts.notes* - leave blank (erase previous values) unless you enter values for RLL or RLS. In that case, *covariate_1* = max.diameter_root or min.diameter_root and coV_1.value=5, as indicated in notes [here](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/DeAngelis_1981_pofe/DeAngelis_1981_pofe_definitions%26abbreviations.csv). 
g. *loaded.from* = DeAngelis_1981_pofe
h.  *loaded.by*= your name

6. When you are done with that, enter values for the sites that are not yet in ForC in a similar way, but not copying values from an existing row. Here's what you should fill in for some of the fields; leave the rest blank.
a. *sites.sitename*= site name as reported in deAngelis
b. *stand.age*=as reported (AS)
c. *dominant.life.form* = woody
d. *veg.notes* = your Forest Type
e. If a single year is given, it goes in *date* , and *date.loc*=8. Then *start.date* and *end.date*=NA. If a range is given, they go in  *start.date* and *end.date*, and *__.date.loc*=8. Then *date* =NA and *date.loc*=9. 
f. *citation.ID* = DeAngelis_1981_pofe
g. *source.notes* = original sources listed in DeAngelis_1981_pofe

**Comment by teixeirak** [comment]
The latest digitized data sheet from @nancyfey123 that I have is [here](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/DeAngelis_1981_pofe). @nancyfey123, if you have a later version, please upload. Otherwise, we will treat this as the latest version.

**Comment by teixeirak** [comment]
@beckybanbury, I wanted to draw your attention to this issue, which relates to the data you've been working on. I should have done this yesterday!

**Comment by beckybanbury** [comment]
@teixeirak, one of the entries in this sheet has no site or plot name (notes say the page was cut off so name was unreadable) - is there a protocol for dealing with this when entering that data?

**Comment by beckybanbury** [comment]
@teixeirak, I have now completed the data entry from this data sheet. Regarding the unnamed site, it isn't clear from the lat/long information where the site is located, so I think it is best if it is left out anyway.

**Comment by teixeirak** [comment]
Thanks! There's another version of the data [here](https://github.com/forc-db/ForC_private/blob/master/intermediate%20data%20sheets/intermediary%20databases%20%26%20reference%20lists/DeAngelis%20NPP_IBP_198/data/woodland.txt); you can probably derive it from that.

**Comment by teixeirak** [comment]
I believe there are also a few more sites that Nancy didn't finish digitizing.  Once that's done, it will be great to close out the task of incorporating this data set!

**Comment by beckybanbury** [comment]
@teixeirak, I have now entered all the data from the digitized set and the raw data set above. Hopefully that completes incorporating this data set! 

I have just gone through to fill in gaps in the data, but those changes haven't been merged yet.

**Comment by teixeirak** [comment]
Wonderful; thank you!
