### ISSUE TITLE
Integrate relevant SRDB data

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#78]
The following steps are required to integrate SRDB data into ForC:
- [ ]  write a script to rearrange SRDB data into the ForC format
- [ ]  write a script to categorize SRDB records into the following categories: 
(1) records from unique sites (identified based on unique lat/long) that can be automatically added, 
(2) records that are definitely duplicates (based on citation and value) and can be excluded (although they may have some valuable supplementary information associated), 
(3) unique measurement records that may be from sites that already have records in ForC, and 
(4) potential duplicate or conflicting records that need to be checked manually.
- [ ] manually check/ merge categories 3-4 above. Note that without this they could still fit within the ForC structure. They would have different site names but be assigned to the correct geographic.area (a more meaningful category than site) and / or flagged as duplicates.
- [ ] revisit original pubs to fill in missing details (again, they can exist in ForC without this; missing information would simply be coded ‘NAC’).

This issue is also recorded [here](https://github.com/PNNL-PREMIS/PREMIS-ghg/issues/7).

**Comment by bpbond** [comment]
A lot hinges on "into the ForC format". This means we'd like to map SRDB -> ForC variables?

**Comment by teixeirak** [comment]
Yes,

1- map the SRDB -> ForC variables
2- create a script to rearrange and add to ForC
3- resolve duplicates/ conflicts
4- fill in missing info as needed

I think it would make sense to schedule a call about this before getting started.

**Comment by teixeirak** [comment]
There are two major steps:
1- map SRDB fields to ForC fields, then write script to draw SRDB data and populate ForC fields
- [ ] @teixeirak will create a document mapping SRDB fields to ForC fields.
2- resolve duplicates.

**Comment by teixeirak** [comment]
I've loaded a recent version of SRDB to ForC_private. I've started a [document mapping SRDB fields to ForC](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/GLOBAL_SRDB_V3_1235/SRDB-ForC%20variable%20mapping.csv).

**Comment by teixeirak** [comment]
I've finished a first pass at this SRDB-ForC mapping document. I hope it makes sense, but it may still be tricky to follow-- let me know what needs to be clarified. This includes all fields from both SRDB and ForC and can be sorted according to the field order in either one-- currently ForC. @bpbond, the "clarifications" field indicates questions for you. The "KAT action needed" field indicates issues that I still need to address, but most of these will be most efficient following your clarifications. This should certainly be enough to get started.

**Comment by dlebauer** [comment]
Looks like the file paths have changed and github redirections are intermittent - the new link to the mapping csv is here: https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/srdb/SRDB-ForC%20variable%20mapping.csv

**Comment by teixeirak** [comment]
Thanks @dlebauer!

**Comment by teixeirak** [comment]
I'd like more clarification on Age_ecosystem and Age_disturbance, focusing just on records for which  Ecosystem_type = forest. 

There are a some instances where there are records for both, and I'm not sure how to interpret them. Does this mean that the forest stand was established (e.g., post-agriculture) according to Age_ecosystem and later disturbed Age_disturbance = 80. Would Age_disturbance always be a stand-clearing disturbance? 

If Age_disturbance>Age_ecosystem (one site), would that just be an error?

**Comment by bpbond** [comment]
>There are a some instances where there are records for both, and I'm not sure how to interpret them. Does this mean that the forest stand was established (e.g., post-agriculture) according to Age_ecosystem and later disturbed Age_disturbance = 80. 

Right. Their meaning is "how long has this been a forest?" (`Age_ecosystem`) and "how long since the last disturbance?" (`Age_disturbance`).

>Would Age_disturbance always be a stand-clearing disturbance?

Usually. I think always? Hard to think of a counter-example.

>If Age_disturbance>Age_ecosystem (one site), would that just be an error?

Yes. Mmm, that's a good check to add to the SRDB QC script.

**Comment by teixeirak** [comment]
The site with is Age_disturbance>Age_ecosystem Tianmu Mountain (2 records).

**Comment by bpbond** [comment]
@teixeirak Thanks! I'll go fix that.

`Stage` is very qualitative and somewhat inconsistent, but even so, there shouldn't be mature records with age < 20. Another good catch. Go with the quantitative number, I think, not the subjective (`Stage`) one, but I'll go check.

**Comment by teixeirak** [comment]
I believe the mapping document is now complete and ready to implement, except:
- [ ] I need to review the manipulations and list those to exclude.  We won't include manipulation types that are specific to soil respiration studies (e.g., litter removal) or some of the more obscure ones (e.g., moose trampling!). 
- [ ]  ForC HISTORY fields need work. Don't do anything with this yet.

**Comment by teixeirak** [comment]
I have (finally!) finished the instructions for merging SRDB into ForC. Instructions are [here](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/srdb).
