### ISSUE TITLE
edit metadata of ForC_simplified

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#81]
@teixeirak,

I was about to edit the [ForC_simplified_metadata](https://github.com/forc-db/ForC/blob/master/ForC_simplified/ForC_simplified_metadata.csv) table to specify that mean was in units of Carbon but it occurred to me that we should probably be more specific, both there and in [measurements_metadata](https://github.com/forc-db/ForC/blob/master/metadata/measurements_metadata.csv) table, and say that the "units depend on the variable and can be found in the VARIABLES table". Originally, when I read "Units dependent on variable.name." I thought it was just about C or OM.

**Comment by teixeirak** [comment]
I've updated in [measurements_metadata](https://github.com/forc-db/ForC/blob/master/metadata/measurements_metadata.csv). 

[ForC_simplified_metadata](https://github.com/forc-db/ForC/blob/master/ForC_simplified/ForC_simplified_metadata.csv) was useful for communicating what I wanted in ForC_simplified, but it will make most sense for this to be pulled directly from the master metadata each time ForC_simplified is updated. Could you please include that in your script? 

To address the conversion to C, please have the script replace the units cell for mean with "Mg C ha-1 (stocks) or Mg C ha-1 yr-1 (fluxes). Variables are identified as stocks of fluxes in the VARIABLES table. Records originally expressed in units of organic matter (OM) were converted to C assuming C =0.48*OM."

**Comment by ValentineHerr** [comment]
Ok I wrote a script that automatically creates the metadata (and recalculates the n, min and max).
I pushed all changes, let me know if you see anything that should be changed.

**Comment by teixeirak** [comment]
Looks great, thanks!
