### ISSUE TITLE
load shiny app code

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#84]
@isamcano, could you please load your code to [this folder](https://github.com/forc-db/ForC/tree/master/shiny/global_data_visualization)?

**Comment by isamcano** [comment]
Hi @teixeirak, I think I don't have 'push access' so it does not allows me to add the files ...

**Comment by teixeirak** [comment]
Can you do a pull request? If that doesn’t work, I can grant you access.

**Comment by teixeirak** [comment]
That worked; thanks!
