### ISSUE TITLE
launch shiny app for data visualization

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#90]
@ValentineHerr, please see if you can launce [@isamcano's shiny app](https://github.com/forc-db/ForC/tree/master/shiny/global_data_visualization).

Below is some information Mauro sent about hosting. Let's create an account dedicated to ForC.

HOSTING

Notice that this example-app  is hosted on  https://bookdown.org/forestgeoguest/. You could create a free account via bookdown.org -- the link to the app would be something like this: https://bookdown.org/user-name/app-name.

Here I explain how you can create a free account https://github.com/forestgeo/learn/issues/18

**Comment by teixeirak** [comment]
A few things I'd like to change:
- [ ] remove "Type of Measurement" (where selecting C is the only option)
- [ ] At the bottom, after "Exploring ForC: A global database of forest carbon stocks and fluxes [ Anderson-Teixeira et al 2018 ]", add a link back to the shiny app script/ ForC repository
- [ ] create the option to exclude some records: "Exclude the following: *managed, *disturbed since stand initiation"
- [ ] control which ages are shown: create a slider for age range (both min and max), also give option to include mature stands of unknown age (999) and unknown age (NAC, NI, NRA).

**Comment by ValentineHerr** [comment]
done!

**Comment by teixeirak** [comment]
This is awesome! 
Is there a way to put a log scale on the age bar? The range where most of the data are is so tiny on that slider. 
Also, please delete the "(999)" and "(NAC, NI, NRA)" text. That was just to clarify for you.

**Comment by bpbond** [comment]
That looks great–nice job @ValentineHerr . 👏

**Comment by ValentineHerr** [comment]
I removed the "(999)" and "(NAC, NI, NRA)" text.

**Comment by ValentineHerr** [comment]
I'll try to do the log scale of the age bar but I don't promise I can do it. Those are widgets that we don't have a lot of control on.... 
If I can't figure it out I'll just make a field to manually enter min and max dbh.

**Comment by ValentineHerr** [comment]
As discussed in person, I made the slider go only until 400 years and added a "check box" to add stands over 400 years old

**Comment by teixeirak** [comment]
@ValentineHerr, I was just playing with this, and there seems to be a bug related to the option to include stands>400 yrs, mature stands of unknown age, unknown age. Could you please look into this?

**Comment by ValentineHerr** [comment]
What is the bug you are experiencing? It seems to be working for me.

**Comment by teixeirak** [comment]
Looks good; thanks.
