### ISSUE TITLE
Bug in ForC-simplified - data for some sites not included

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#95]
@ValentineHerr, I just found some sort of bug with ForC-simplified. There's a small portion (n=164) of records where data from the sites table did not make it into ForC-simplified (all NA's).

**Comment by ValentineHerr** [comment]
Indeed... There are all because of inconsistencies between _sites.sitename_ in SITES table and _sites.sitename_ in MEASUREMENT table.
I'll spend some time to fix that.

**Comment by ValentineHerr** [comment]
I believe I fixed the problem (mostly hidden spaces at the end of the site names).
