### ISSUE TITLE
update R code to account for minor data changes

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#97]
@ValentineHerr, please update R code as needed to account for the following changes:

- [x] In [this commit](https://github.com/forc-db/ForC/commit/8323c7b4ceaece7e3cb6e30c423af10713cb3793), I replaced "<<100%" with "minor" in the percent.mortality field. Please update any R code that used this. I believe the only one is [this](https://github.com/forc-db/ForC/blob/master/scripts/Database_manipulation/Create_ForC_simplified.R).
- [x] changed variable name "R_soil_het" to "R_het_soil"
- [x] changed variable name ANPP_litterfall_3 to ANPP_litterfall_0

**Comment by ValentineHerr** [comment]
done
