### ISSUE TITLE
Incorporate Cook-Patton data

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#98]
@CookPatton, @ValentineHerr -

I'm starting preparation's to incorporate Susan Cook-Patton's database into ForC. Example data are [here](https://github.com/forc-db/ForC_private/tree/master/data%20to%20add/Cook-Patton).

The first step will be to create a detailed document mapping how Susan's data should be transferred to ForC (similar to what we did for SRDB; issue #78). I will start on this process.

@CookPatton, most of your data fields are fairly self-explanatory, but there are a few that I'm unsure how to interpret. Do you have a metadata file? (Alternatively, I can send a list of fields in question.)

**Comment by teixeirak** [comment]
I have started the [variable mapping document](https://github.com/forc-db/ForC_private/blob/master/data%20to%20add/Cook-Patton/CP-ForC%20variable%20mapping.csv). 
@CookPatton, I have a number of questions/clarifications for you (clarifications field). It may make sense to wait and go over this together in person.

**Comment by CookPatton** [comment]
@teixeirak, @ValentineHerr 

Hi Krista and Valentine,

Excuse my delay in response - my boss went on vacation and I went rogue. I wanted to confirm that he was okay with putting all data up on ForCdb before I responded. He was as enthusiastic as me, so full sails ahead and Krista thanks for all your work on this already! We almost have the fully error checked data, so I can share that soon.  In the meantime, I can answer any questions about specific fields. My instruction sheet is here [https://tnc.box.com/s/v59vh9h1o8r1593bb4ujaes0pkjv9tlo](url) but this is a dynamic document that I haven't updated recently. Its probably easier to just send me the fields in question and I can provide details.

Cheers,

Susan

**Comment by CookPatton** [comment]
@teixeirak - It looks like you may have already flagged the issues, but I will need some advice on how to edit the variable mapping document you provided

**Comment by teixeirak** [comment]
I believe this is fully ready to go once the data are ready to go public.

**Comment by teixeirak** [comment]
@ValentineHerr , I believe we can go ahead and do this merge now. Assuming its fast, it would be great if you could do it soon, and also update the map/ figures.

**Comment by ValentineHerr** [comment]
@teixeirak, see [this comment](https://github.com/forc-db/GROA/commit/6fe525ce8a6de6eee140187f2e81182f806215dc#commitcomment-41633858) and let me know if the refor.type mapping is enough or if I should try to merge back that sites.sitename column.

**Comment by teixeirak** [comment]
The last 2 commits (one in ForC, one here) apply the same rule to the new Sierra_2012_tcai data as the previous.

**Comment by teixeirak** [comment]
> Also, I think I never dealt with the soil data... did you expect to have that imported as well? (maybe I did and don't recall)

No, we don't need to do soil.

**Comment by teixeirak** [comment]
Please don't import the other duplicates. I took a quick look. For one (`Subtropical broad-leaved evergreen forest chronosequence`) the ForC estimate is more comprehensive. For the other (`Fazenda Vitoria 2`), its hard to judge which is "better" (both taken from a stacked bar graph with many components, and may include slightly different components).

**Comment by teixeirak** [comment]
I believe we can now go ahead with the import.

**Comment by ValentineHerr** [comment]
Ok thanks!

Is it okay if I add a column to ForC tables for the GROA IDs? (e.g column GROA.site.ID in the SITES table?), 

I think it will be necessary if we want to re-import GROA if it gets expanded.

If we don't want the new column, I need to make sure I add the info somewhere retrievable (I don't think this was mapped like that but it should not be too hard to add something in the notes.)

**Comment by teixeirak** [comment]
Sure, that’s fine. Thanks for working on this!

**Comment by dlebauer** [comment]
Pardon me for speaking up with only a cursory understanding but 

> Is it okay if I add a column to ForC tables for the GROA IDs? (e.g column GROA.site.ID in the SITES table?),

One drawback of this is that it adds a single column to the table that is a) mostly empty, b) specific to a particular external dataset and c) only serves the purpose of recording where the data came from in GROA (for re-importing and other valuable purposes) but ... another way to do this would be to keep a table (e.g. metadata/groasites_lookup.csv) with two columns, sites.ID and GROA.site.ID.

**Comment by teixeirak** [comment]
Thanks, David. I like that.

**Comment by ValentineHerr** [comment]
Yes, this is a good idea. I’ll do that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
